{
  description = "Docker Compose files for 3 container variants × 3 profiles";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    buildJson = builtins.fromJSON (builtins.readFile ../build.json);
    registry = buildJson.registry;

    # ── Compose template (shared across all 3 images) ─────────────────
    mkCompose = { imageName, imageTag ? "latest", variant }: ''
      # ╔══════════════════════════════════════════════════════════════════╗
      # ║ Diego's Dev Environment — ${variant}                            ║
      # ║ DO NOT EDIT — generated by cc_containers-compose/src/flake.nix ║
      # ║ Rebuild: build.sh build                                        ║
      # ╠══════════════════════════════════════════════════════════════════╣
      # ║ Profiles: cli, gui, tty                                        ║
      # ║ Usage:                                                          ║
      # ║   docker compose --profile cli up      # interactive shell     ║
      # ║   docker compose --profile gui up      # desktop integrated    ║
      # ║   docker compose run --rm tty cmd      # run + exit            ║
      # ║ Preferred: dtk.sh containers ${variant} {cli|gui|tty}          ║
      # ╚══════════════════════════════════════════════════════════════════╝

      x-common: &common
        image: ${registry}/${imageName}:${imageTag}
        user: "1000:1000"
        working_dir: /home/diego
        network_mode: host
        privileged: true
        environment:
          - HOME=/home/diego
          - USER=diego
          - TERM=xterm-256color
          - LANG=en_US.UTF-8
          - PATH=/home/diego/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/sbin
        volumes:
          - ''${HOME:-/home/diego}:/home/diego
          - /var/run/docker.sock:/var/run/docker.sock
        labels:
          diego.managed-by: "dtk.sh"
          diego.image.variant: "${variant}"

      services:
        # ── CLI: headless dev environment ────────────────────────────────
        cli:
          <<: *common
          container_name: diego-${variant}-cli
          hostname: ''${HOSTNAME:-dev}-cli
          stdin_open: true
          tty: true
          pid: host
          volumes:
            - ''${HOME:-/home/diego}:/home/diego
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/wireguard:/etc/wireguard:ro
            - /opt:/opt
          profiles: [cli]

        # ── GUI: full desktop integration ────────────────────────────────
        gui:
          <<: *common
          container_name: diego-${variant}-gui
          hostname: ''${HOSTNAME:-dev}-gui
          stdin_open: true
          tty: true
          pid: host
          ipc: host
          security_opt:
            - label=disable
            - apparmor=unconfined
          environment:
            - HOME=/home/diego
            - USER=diego
            - TERM=xterm-256color
            - LANG=en_US.UTF-8
            - DISPLAY=''${DISPLAY:-}
            - WAYLAND_DISPLAY=''${WAYLAND_DISPLAY:-}
            - XDG_RUNTIME_DIR=''${XDG_RUNTIME_DIR:-/run/user/1000}
            - DBUS_SESSION_BUS_ADDRESS=''${DBUS_SESSION_BUS_ADDRESS:-}
            - PULSE_SERVER=''${PULSE_SERVER:-}
            - SHELL=fish
            - PATH=/home/diego/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/sbin
          volumes:
            - ''${HOME:-/home/diego}:/home/diego:rslave
            - /tmp:/tmp:rslave
            - /dev:/dev:rslave
            - /sys:/sys:rslave
            - ''${XDG_RUNTIME_DIR:-/run/user/1000}:''${XDG_RUNTIME_DIR:-/run/user/1000}:rslave
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/wireguard:/etc/wireguard:ro
            - /opt:/opt
            - /nix:/nix
            - /var/log/journal:/var/log/journal
            - /etc/hosts:/etc/hosts:ro
            - /etc/resolv.conf:/etc/resolv.conf:ro
            - /etc/hostname:/etc/hostname:ro
          profiles: [gui]

        # ── TTY: non-interactive (CI, scripts, Dagu, cron) ──────────────
        tty:
          <<: *common
          container_name: diego-${variant}-tty
          hostname: ''${HOSTNAME:-dev}-tty
          pid: host
          volumes:
            - ''${HOME:-/home/diego}:/home/diego
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/wireguard:/etc/wireguard:ro
            - /opt:/opt
          profiles: [tty]
    '';

  in {
    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      default = pkgs.runCommand "containers-compose" {} ''
        mkdir -p $out
        cp ${pkgs.writeText "compose-deb-nix.yaml" (mkCompose {
          imageName = "diego-deb-nix";
          variant = "deb-nix";
        })} $out/compose-deb-nix.yaml

        cp ${pkgs.writeText "compose-deb-apt.yaml" (mkCompose {
          imageName = "diego-deb-apt";
          variant = "deb-apt";
        })} $out/compose-deb-apt.yaml

        cp ${pkgs.writeText "compose-nixos-hm.yaml" (mkCompose {
          imageName = "diego-nixos-hm";
          variant = "nixos-hm";
        })} $out/compose-nixos-hm.yaml

        # Copy build.json for reference
        cp ${../build.json} $out/build.json
      '';
    });
  };
}
