# NODE_PATH for shared ~/.node_modules (ESM doesn't read NODE_PATH, but CJS + tsx do)
set -gx NODE_PATH "$HOME/.node_modules/node_modules"

# Starship prompt
if command -v starship &>/dev/null
  starship init fish | source
end

# Zoxide
if command -v zoxide &>/dev/null
  zoxide init fish | source
end

# Atuin (shell history) — keep arrow-up for classic per-command recall, Ctrl+R for atuin
if command -v atuin &>/dev/null
  atuin init fish --disable-up-arrow | source
end

# FZF
if command -v fzf &>/dev/null
  fzf --fish | source
end

# Direnv
if command -v direnv &>/dev/null
  direnv hook fish | source
end

# API keys from vault (read at shell init, not baked into Nix store)
if test -f ~/git/cloud-vault/A0_keys/providers/anthropic/api-key_opaque
  set -gx ANTHROPIC_API_KEY (command cat ~/git/cloud-vault/A0_keys/providers/anthropic/api-key_opaque)
end

# Vault env keys — fish dialect (generated by vault/build.sh env)
# Source of truth: ~/git/cloud-vault/vault-keys.json
if test -f ~/git/cloud-vault/vault-keys-fish.fish
  source ~/git/cloud-vault/vault-keys-fish.fish
end

# Vi mode
fish_vi_key_bindings

# Keybinding: Ctrl+P to search available commands with fzf
bind \cp '__fzf_search_commands'
bind -M insert \cp '__fzf_search_commands'

# NVM via bass (if available)
# set -gx NVM_DIR $HOME/.nvm

# Ensure user PATH entries are set even when __HM_SESS_VARS_SOURCED is
# inherited from a parent process (e.g. Plasma → Konsole).
# fish_add_path is idempotent: no duplicates added.
if test -d /mnt/shared/tools/scripts
  fish_add_path -g --path /mnt/shared/tools/scripts
end
for dir in /mnt/shared/tools/devops/bin /mnt/shared/tools/data/bin /mnt/shared/tools/dev/bin /mnt/shared/tools/base/bin
  if test -d $dir
    fish_add_path -g --path $dir
  end
end
if test -d $HOME/.npm-global/bin
  fish_add_path -g --path $HOME/.npm-global/bin
end
if test -d $HOME/.cargo/bin
  fish_add_path -g --path $HOME/.cargo/bin
end
# FINAL PATH ORDER (last --move wins the front):
#   ~/.local/bin  →  ~/.nix-profile/bin  →  everything else
# ~/.local/bin MUST beat nix-profile: the Authelia bearer-injecting curl/wget
# wrappers live there (curl-wget-wrapper.nix) — the previous version moved
# nix-profile alone to the front, silently bypassing the wrappers in fish
# (2026-08-08 audit). nix-profile still beats npm/cargo/termux copies, and
# stale `claude` shims in ~/.local/bin are handled by claude-fix/cleanup,
# not by PATH games. --move --path is REQUIRED (a plain fish_add_path skips
# already-present components instead of promoting them); -g keeps scope
# consistent (bare fish_add_path writes UNIVERSAL vars that persist forever).
if test -d $HOME/.nix-profile/bin
  fish_add_path -g --move --path $HOME/.nix-profile/bin
end
if test -d $HOME/.local/bin
  fish_add_path -g --move --path $HOME/.local/bin
end

# Authelia OIDC credentials (vault paths)
set -gx AUTHELIA_OIDC_CREDENTIALS_DIR "$HOME/git/cloud-vault/A0_keys/providers/authelia/signed-bearer_jwt/credentials"
set -gx AUTHELIA_OIDC_TOKENS_DIR "$HOME/git/cloud-vault/A0_keys/providers/authelia/signed-bearer_jwt/tokens"
set -gx AUTHELIA_OIDC_CLIENT_ID "claude-admin"
set -gx AUTHELIA_TOKEN_URL "https://auth.diegonmarcos.com/api/oidc/token"

# /etc self-heal — body in scripts/etc-self-heal.sh (deployed on PATH).
# Moved here from flake.nix per the no-inline-scripts decree (2026-08-08).
command -q etc-self-heal; and etc-self-heal 2>/dev/null

# my-webserver auto-start (single start site — the flake
# copy was deleted; wrapper is idempotent via PID file).
set -g __httpd_port 8000
if command -q my-webserver
  my-webserver start >/dev/null 2>&1
  set -g __httpd_pid (command cat ~/.cache/my-webserver.pid 2>/dev/null)
end

# FZF appearance (the fzf_file/history/cd rebinds that lived in flake.nix
# were deleted 2026-08-08 — they clobbered atuin Ctrl+R and fzf --fish).
set -gx FZF_DEFAULT_OPTS "--height 40% --layout=reverse --border"

# Local overrides
if test -f ~/.config/fish/config.local.fish
  source ~/.config/fish/config.local.fish
end

# The old `functions -e up` de-shadow line is GONE: `up` is now a declared
# alias for flakes.switch (modules/data/fish-commands.json), so erasing it
# would delete the real thing. The shadow class it defended against is fixed
# at the source — flake.nix no longer defines any fish alias.
