# desktop/window-rules.nix — KWin window rules, data-driven from window-rules.json.
#
# WHY THIS EXISTS (2026-08-12)
# ───────────────────────────
# `build.sh switch` opens THREE windows and all of them landed on whatever
# desktop happened to be focused, burying the work they interrupted:
#   * Konsole "Nix Switch Progress"           — flakes-switch-progress-logs
#   * Konsole "NixOS switch — live dashboard" — src/scripts/switch-progress.sh
#   * kdialog "NixOS switch — LIVE DASHBOARD" — same script
#
# Plasma 6 removed kstart's --desktop flag (kstart 6.2.5 offers only
# --desktopfile/--application), so there is no way to launch a window onto a
# given virtual desktop from the command line any more. A KWin rule is the
# supported mechanism, and it also has no race: the rule applies at window
# creation, whereas the alternative (KWin scripting after launch, as
# default-session-launcher.sh does for the login layout) has to find the window
# first and can miss a short-lived one.
#
# plasma.nix:384 claims "window-rules are now generated by ./session-template.nix
# from ./session-template.json" — BOTH OF THOSE FILES ARE GONE. That comment is
# stale and there was no window-rule mechanism left at all; this module is it.
#
# WHY kwriteconfig6 AND NOT xdg.configFile
# ────────────────────────────────────────
# KWin rewrites ~/.config/kwinrulesrc wholesale whenever a rule is touched in
# System Settings. A /nix/store symlink there would be replaced by a real file
# on the first GUI edit and the declaration would silently stop applying — the
# identical failure konsolerc, "Profile 1.profile" and baloofilerc all hit
# (see app_especific/konsole.nix). Writing individual keys re-asserts ours on
# every switch while leaving any rule added by hand untouched.
{ config, lib, pkgs, ... }:

let
  data = builtins.fromJSON (builtins.readFile ./window-rules.json);
  kw = "${pkgs.kdePackages.kconfig}/bin/kwriteconfig6";
  kr = "${pkgs.kdePackages.kconfig}/bin/kreadconfig6";

  # One kwriteconfig6 call per key. `rules=` in [General] is a comma-separated
  # index of section names; each rule then lives in its own [<key>] section.
  mkRule = r: ''
    ${kw} --file kwinrulesrc --group "${r.key}" --key Description "${r.description}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key title "${r.title}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key titlematch "${toString r.titlematch}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key wmclass "${r.wmclass}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key wmclassmatch "${toString r.wmclassmatch}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key wmclasscomplete "${if r.wmclasscomplete then "true" else "false"}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key desktops "${r.desktops}"
    ${kw} --file kwinrulesrc --group "${r.key}" --key desktopsrule "${toString r.desktopsrule}"
  '';

  ruleKeys = map (r: r.key) data.rules;
in
{
  home.activation.kwinWindowRules = lib.hm.dag.entryAfter [ "writeBoundary" "configure-plasma" ] ''
    (
    ${lib.concatMapStringsSep "\n" mkRule data.rules}

    # [General].rules is an INDEX — a rule section KWin cannot find listed here
    # is ignored entirely. Merge rather than overwrite so hand-made rules
    # survive: read the current list, append only the keys that are missing.
    _cur="$(${kr} --file kwinrulesrc --group General --key rules 2>/dev/null || true)"
    _new="$_cur"
    for _k in ${lib.concatStringsSep " " ruleKeys}; do
      case ",$_new," in
        *",$_k,"*) ;;
        *) if [ -z "$_new" ]; then _new="$_k"; else _new="$_new,$_k"; fi ;;
      esac
    done
    if [ "$_new" != "$_cur" ]; then
      $DRY_RUN_CMD ${kw} --file kwinrulesrc --group General --key rules "$_new"
      # count must match, or KWin reads a truncated list.
      $DRY_RUN_CMD ${kw} --file kwinrulesrc --group General --key count \
        "$(printf '%s' "$_new" | ${pkgs.gawk}/bin/awk -F, '{print NF}')"
      echo "[kwin-rules] rules index: '$_cur' -> '$_new'"
    fi

    # Ask KWin to re-read. Harmless when it is not running (tty, early
    # activation); the rules load at next start regardless.
    ${pkgs.kdePackages.qttools}/bin/qdbus org.kde.KWin /KWin reconfigure \
      >/dev/null 2>&1 || true
    ) || echo "[kwin-rules] subshell failed; HM chain continues"
  '';
}
