#!/usr/bin/env python3
"""Data-driven design generator for Garmin watch faces.

Reads a design's faces/<id>/design.json and emits two BUILD ARTIFACTS
(both gitignored — regenerated every `build.sh build`):

  1. faces/<id>/source/gen/DesignConfig.mc
       Monkey C `module DesignConfig` holding every geometry constant +
       the CIRCLES table the renderer iterates. The .mc source NEVER
       hardcodes geometry — it reads these constants.

  2. faces/<id>/resources/drawables/launcher_icon.png
       The 2-circles motif (gray strokes on black) drawn from the SAME
       geometry at a fixed sample time, so the launcher icon always
       matches the live face. Pure-stdlib PNG (zlib only — no PIL).

Usage: gen-design.py <design_dir>
"""

import json
import math
import struct
import sys
import zlib
from pathlib import Path


# ── CIRCLES table column order (kept in lockstep with TwoCirclesView.mc) ──
#   [angleSrcIsHours, centerDistPct, radiusPct,
#    ticksOn, tickCount, tickLenPct,
#    handOn, handSrcIsHours, handLenPct]
def _circle_row(c):
    ang_hours = c["angle_source"] == "hours"
    ticks = c.get("ticks", {})
    hand = c.get("hand", {})
    return [
        ang_hours,
        float(c["center_distance_pct"]),
        float(c["radius_pct"]),
        bool(ticks.get("enabled", False)),
        int(ticks.get("count", 0)),
        float(ticks.get("len_pct", 0.0)),
        bool(hand.get("enabled", False)),
        hand.get("angle_source", "minutes") == "hours",
        float(hand.get("len_pct", 0.0)),
    ]


def _mc_literal(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        # Force a Float literal with a decimal point.
        s = repr(v)
        return s if ("." in s or "e" in s) else s + ".0"
    raise TypeError(v)


def gen_design_config(design, out_path):
    g = design["geometry"]
    rows = [_circle_row(c) for c in g["circles"]]
    rows_mc = ",\n        ".join(
        "[" + ", ".join(_mc_literal(x) for x in row) + "]" for row in rows
    )
    banner = (
        "// GENERATED by lib/gen-design.py from faces/{}/design.json — DO NOT EDIT.\n"
        "// Tune geometry in design.json, then `build.sh build`.\n"
    ).format(design["id"])
    body = """{banner}import Toybox.Lang;

module DesignConfig {{
    const BACKGROUND_COLOR = {bg};
    const STROKE_COLOR = {stroke};
    const STROKE_WIDTH_PX = {pen};
    const ANTIALIAS = {aa};

    // Each row: [angleSrcIsHours, centerDistPct, radiusPct,
    //            ticksOn, tickCount, tickLenPct,
    //            handOn, handSrcIsHours, handLenPct]
    const CIRCLES = [
        {rows}
    ];
}}
""".format(
        banner=banner,
        bg=g["background_color"],
        stroke=g["stroke_color"],
        pen=int(g["stroke_width_px"]),
        aa=_mc_literal(bool(g.get("antialias", True))),
        rows=rows_mc,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body)


# ── Minimal RGB PNG writer (stdlib only) ──────────────────────────────────
def _png(width, height, pixels):
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type 0 (None)
        row = y * width * 3
        raw.extend(pixels[row : row + width * 3])
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)  # 8-bit RGB
    idat = zlib.compress(bytes(raw), 9)
    return sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


def _rgb(hexstr):
    v = int(str(hexstr), 0) & 0xFFFFFF
    return ((v >> 16) & 0xFF, (v >> 8) & 0xFF, v & 0xFF)


def gen_launcher_icon(design, out_path, size=40):
    g = design["geometry"]
    bg = _rgb(g["background_color"])
    stroke = _rgb(g["stroke_color"])
    px = bytearray(bg * (size * size))

    cx = cy = size / 2.0
    r = size / 2.0 - 1.0
    # Sample time for the icon: 10:10 (classic watch pose) -> pleasant motif.
    f_min = 10 / 60.0
    f_hour = (10 + 10 / 60.0) / 12.0

    def put(x, y):
        xi, yi = int(round(x)), int(round(y))
        if 0 <= xi < size and 0 <= yi < size:
            o = (yi * size + xi) * 3
            px[o], px[o + 1], px[o + 2] = stroke

    def ring(ccx, ccy, rad):
        steps = max(24, int(rad * 8))
        for i in range(steps):
            a = (i / steps) * 2 * math.pi
            put(ccx + math.sin(a) * rad, ccy - math.cos(a) * rad)

    for c in g["circles"]:
        af = f_hour if c["angle_source"] == "hours" else f_min
        th = af * 2 * math.pi
        dist = float(c["center_distance_pct"]) * r
        rad = float(c["radius_pct"]) * r
        ccx = cx + math.sin(th) * dist
        ccy = cy - math.cos(th) * dist
        ring(ccx, ccy, rad)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(_png(size, size, px))


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-design.py <design_dir>")
    design_dir = Path(sys.argv[1]).resolve()
    design = json.loads((design_dir / "design.json").read_text())
    gen_design_config(design, design_dir / "source" / "gen" / "DesignConfig.mc")
    gen_launcher_icon(design, design_dir / "resources" / "drawables" / "launcher_icon.png")
    print("[gen-design] {}: DesignConfig.mc + launcher_icon.png".format(design["id"]))


if __name__ == "__main__":
    main()
