/*
 * SensorFW.cpp — IIO-backed data source for the Waydroid sensors HAL.
 *
 * Reads the host Linux IIO accelerometer (/sys/bus/iio) and exposes it through the
 * exact SensorFW surface that Sensors.cpp expects. Config (IIO device name, poll
 * interval, mount matrix) is read from a KEY=VALUE file pointed to by the
 * WAYDROID_SENSORS_CONF env var — generated by build.sh from build.json (data-driven).
 *
 * © 2026 Diego Nepomuceno Marcos, GPL-3.0. Derives from droidian/waydroid-sensors
 * (© 2021 Waydroid Project, Erfan Abdi), GPL-3.0.
 */

#include "SensorFW.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace waydroid {

/* ---- helpers ------------------------------------------------------------ */

static bool read_double_file(const std::string& path, double* out) {
    gchar* buf = nullptr; gsize len = 0;
    if (!g_file_get_contents(path.c_str(), &buf, &len, nullptr)) return false;
    bool ok = (sscanf(buf, "%lf", out) == 1);
    g_free(buf);
    return ok;
}

static int axis_src(const char* v) {
    if (!v) return -1;
    if (v[0] == 'x' || v[0] == 'X') return 0;
    if (v[0] == 'y' || v[0] == 'Y') return 1;
    if (v[0] == 'z' || v[0] == 'Z') return 2;
    return -1;
}

/* ---- lifecycle ---------------------------------------------------------- */

SensorFW::SensorFW() {
    loadConfig();
    if (resolveAccelDevice()) {
        mAvailable[ID_ACCELEROMETER] = true;
        g_message("waydroid-sensors: accelerometer '%s' at %s (scale=%g, poll=%dms)",
                  mIioName.c_str(), mAccelPath.c_str(), mAccelScale, mPollMs);
    } else {
        g_warning("waydroid-sensors: no IIO accelerometer named '%s' found — "
                  "no sensors will be exported", mIioName.c_str());
    }
}

SensorFW::~SensorFW() {
    if (mTimerId) { g_source_remove(mTimerId); mTimerId = 0; }
}

bool SensorFW::loadConfig() {
    // WAYDROID_SENSORS_CONF wins (set by build.sh for dist/ testing). When unset —
    // e.g. when waydroid-container launches the system-PATH daemon with NO environment
    // — fall back to the conventional install path so the daemon stays data-driven.
    // This path MUST match build.json runtime.conf_install_path (rendered there via
    // environment.etc by the host flake). Missing file → harmless built-in defaults.
    const char* env = getenv("WAYDROID_SENSORS_CONF");
    const char* conf = (env && *env) ? env
                                     : "/etc/waydroid-sensors/waydroid-sensors.conf";
    gchar* buf = nullptr; gsize len = 0;
    if (!g_file_get_contents(conf, &buf, &len, nullptr)) {
        g_message("waydroid-sensors: no readable conf at %s — using built-in defaults", conf);
        return false;
    }
    g_message("waydroid-sensors: loaded conf %s", conf);
    gchar** lines = g_strsplit(buf, "\n", -1);
    g_free(buf);
    for (int i = 0; lines[i]; i++) {
        gchar* line = g_strstrip(lines[i]);
        if (!*line || line[0] == '#') continue;
        gchar* eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';
        const char* key = g_strstrip(line);
        const char* val = g_strstrip(eq + 1);
        if      (!strcmp(key, "IIO_NAME"))         mIioName = val;
        else if (!strcmp(key, "POLL_INTERVAL_MS")) mPollMs  = atoi(val);
        else if (!strcmp(key, "POLL_WAIT_MS"))     mPollWaitMs = atoi(val);
        else if (!strcmp(key, "AXIS_X_SRC"))       mMap[0].src  = axis_src(val);
        else if (!strcmp(key, "AXIS_X_SIGN"))      mMap[0].sign = atoi(val) < 0 ? -1 : 1;
        else if (!strcmp(key, "AXIS_Y_SRC"))       mMap[1].src  = axis_src(val);
        else if (!strcmp(key, "AXIS_Y_SIGN"))      mMap[1].sign = atoi(val) < 0 ? -1 : 1;
        else if (!strcmp(key, "AXIS_Z_SRC"))       mMap[2].src  = axis_src(val);
        else if (!strcmp(key, "AXIS_Z_SIGN"))      mMap[2].sign = atoi(val) < 0 ? -1 : 1;
    }
    g_strfreev(lines);
    if (mPollMs < 20) mPollMs = 20;
    if (mPollWaitMs < 100) mPollWaitMs = 100;  // floor: never spin SensorService init too tightly
    for (int i = 0; i < 3; i++) if (mMap[i].src < 0) mMap[i].src = i;
    return true;
}

bool SensorFW::resolveAccelDevice() {
    const char* base = "/sys/bus/iio/devices";
    GDir* dir = g_dir_open(base, 0, nullptr);
    if (!dir) return false;
    const gchar* ent;
    bool found = false;
    while ((ent = g_dir_read_name(dir))) {
        if (strncmp(ent, "iio:device", 10) != 0) continue;
        std::string dev = std::string(base) + "/" + ent;
        gchar* name = nullptr; gsize len = 0;
        if (!g_file_get_contents((dev + "/name").c_str(), &name, &len, nullptr)) continue;
        gchar* nm = g_strstrip(name);
        bool match = (mIioName == nm);
        g_free(name);
        if (!match) continue;
        // require accel channels
        if (!g_file_test((dev + "/in_accel_x_raw").c_str(), G_FILE_TEST_EXISTS)) continue;
        mAccelPath = dev;
        double scale = 1.0;
        read_double_file(dev + "/in_accel_scale", &scale);   // raw*scale -> m/s^2
        mAccelScale = scale;
        found = true;
        break;
    }
    g_dir_close(dir);
    return found;
}

bool SensorFW::readAccelRaw(double* ax, double* ay, double* az) {
    if (mAccelPath.empty()) return false;
    double raw[3];
    const char* ch[3] = { "/in_accel_x_raw", "/in_accel_y_raw", "/in_accel_z_raw" };
    for (int i = 0; i < 3; i++)
        if (!read_double_file(mAccelPath + ch[i], &raw[i])) return false;
    for (int i = 0; i < 3; i++) raw[i] *= mAccelScale;       // -> m/s^2
    *ax = mMap[0].sign * raw[mMap[0].src];
    *ay = mMap[1].sign * raw[mMap[1].src];
    *az = mMap[2].sign * raw[mMap[2].src];
    return true;
}

/* ---- registration / polling -------------------------------------------- */

static gboolean timer_cb(gpointer u) {
    static_cast<SensorFW*>(u)->pollOnce();
    return G_SOURCE_CONTINUE;
}

void SensorFW::RegisterSensors(sensor_event_cb_t cb, void* userdata) {
    mCb = cb;
    mUserdata = userdata;
    if (mAvailable[ID_ACCELEROMETER] && !mTimerId)
        mTimerId = g_timeout_add(mPollMs, timer_cb, this);
}

void SensorFW::pollOnce() {
    if (!mCb) return;
    // Only sample IIO + publish a fresh reading while the accelerometer is enabled.
    if (mEnabled[ID_ACCELEROMETER]) {
        double ax, ay, az;
        if (readAccelRaw(&ax, &ay, &az)) {
            mAccelX = (int) lround(ax * 100.0);   // centi-m/s^2 (Sensors.cpp /100)
            mAccelY = (int) lround(ay * 100.0);
            mAccelZ = (int) lround(az * 100.0);
            mAccelTs = (uint64_t) g_get_monotonic_time() * 1000ULL;  // ns, strictly increasing
        }
    }
    // ALWAYS wake the consumer's poll() loop, even when no sensor is enabled. The upstream
    // callback only enqueues an event when GetAccelerometerEvent() returns 0 (enabled), but
    // it always quits the waiting g_main_loop — so poll() returns within mPollMs instead of
    // blocking forever. This is what stops SensorService's init-time poll() (issued before
    // any activate()) from deadlocking system_server and freezing Waydroid on boot.
    mCb(mUserdata, ID_ACCELEROMETER);
}

/* ---- query / control --------------------------------------------------- */

bool SensorFW::IsSensorAvailable(int id) { return ID_CHECK(id) && mAvailable[id]; }
bool SensorFW::IsSensorEventEnable(int id) { return ID_CHECK(id) && mEnabled[id]; }

int SensorFW::EnableSensorEvents(int id) {
    if (!ID_CHECK(id) || !mAvailable[id]) return -1;
    mEnabled[id] = true;
    return 0;
}
int SensorFW::DisableSensorEvents(int id) {
    if (!ID_CHECK(id)) return -1;
    mEnabled[id] = false;
    return 0;
}

int SensorFW::GetAccelerometerEvent(uint64_t* ts, int* x, int* y, int* z) {
    // Gate on enabled (not just available): the timer wakes poll() every interval even
    // when disabled, so returning -1 here keeps those wakeups event-free (no spurious data).
    if (!mAvailable[ID_ACCELEROMETER] || !mEnabled[ID_ACCELEROMETER]) return -1;
    *ts = mAccelTs; *x = mAccelX; *y = mAccelY; *z = mAccelZ;
    return 0;
}

/* Unsupported sensors (phase 1 = accelerometer only). Stubs so Sensors.cpp links;
 * Sensors.cpp never reaches these (IsSensorAvailable gates the list + callbacks). */
int SensorFW::GetGyroscopeEvent(uint64_t*, int*, int*, int*) { return -1; }
int SensorFW::GetHumidityEvent(uint64_t*, unsigned*) { return -1; }
int SensorFW::GetLightEvent(uint64_t*, unsigned*) { return -1; }
int SensorFW::GetMagnetometerEvent(uint64_t*, int*, int*, int*, int*, int*, int*, int*) { return -1; }
int SensorFW::GetOrientationEvent(uint64_t*, int*) { return -1; }
int SensorFW::GetPressureEvent(uint64_t*, unsigned*) { return -1; }
int SensorFW::GetProximityEvent(uint64_t*, unsigned*, bool*) { return -1; }
int SensorFW::GetStepcounterEvent(uint64_t*, unsigned*) { return -1; }
int SensorFW::GetTemperatureEvent(uint64_t*, unsigned*) { return -1; }

}  // namespace waydroid
