# Termux SSHD — declarative SSH daemon on port ${toString sshPort}, openssh-based.
#
# Recipe taken from the nix-on-droid maintainers (issue #32):
# https://github.com/nix-community/nix-on-droid/issues/32
#
# Why these specifics:
#   1. Run sshd via $HOME/.nix-profile/bin/sshd (the user-profile path),
#      NOT /nix/store/.../bin/sshd. The profile path is what nix-on-droid's
#      proot wrapper resolves correctly for privilege-separation re-exec.
#   2. Pass `-f <absolute>/sshd_config`. A real config file (with HostKey
#      and Port) works where inline `-o HostKey=...` flags fail under proot.
#   3. Connecting shells get `/bin/sh` which does NOT read `.bashrc` —
#      put nix env loading in `~/.profile` so PATH and tooling resolve.
#
# Provides: cloud-ide-sshd command (start|stop|status|restart) — serves the Cloud IDE APK over 127.0.0.1 and WG.
# Trusted pubkeys: data-driven from data/authorized-keys.json.
{ config, pkgs, lib, ... }:

let
  # Use the stock openssh from the default closure. The 8.9p1 pin was a
  # workaround for proot's execveat-with-fd issue, but the rescue path
  # (sh -c command) doesn't trigger that code path on stock 9.x — and
  # building 8.9p1 from source on aarch64 phone (~10min compile) is too
  # slow on a swap-thrashing device. Pin source kept in pkgs/openssh-pinned.nix
  # for emergency wire-up if a future kernel/proot combo needs it.
  opensshPinned = pkgs.openssh;

  # NOTE: prootPatched (pkgs/proot-termux-patched/) is currently disabled.
  # Building it natively on aarch64 pulls pkgs.pkgsStatic.talloc, which drags
  # in python3-static + tzdata-static — and tzdata-static fails to build on
  # aarch64-musl (Makefile:815 to2050new.tzs error). Until either:
  #   (a) nixpkgs fixes tzdata-static-aarch64-musl, OR
  #   (b) we build the patched proot via cross-compile from x86_64 cache,
  # we rely on OpenSSH 8.9p1 pin (see opensshPinned) which mostly avoids
  # the proot execveat-with-fd path. The patch is still on disk in
  # pkgs/proot-termux-patched/ ready to wire up when one of those lands.

  authData = builtins.fromJSON (builtins.readFile ../data/authorized-keys.json);
  authorizedKeysContent =
    lib.concatStringsSep "\n" authData.trusted_pubkeys + "\n";
  # Cloud IDE APK pubkey, sops-encrypted (decrypted at activation).
  secretsFile = ./secrets.yaml;

  # Read the WG IP + SSH port from build.json (data-driven). sshd binds ONLY
  # to wgIp — no public exposure. If wg0 is down, sshd refuses to start
  # rather than fall back to listening on all interfaces.
  #
  # Default port is 8023, NOT 8022 — on this device 8022 hits EADDRINUSE
  # despite /proc/net/tcp showing the port free (suspected kernel TIME_WAIT
  # or Android sandbox lock invisible to proot's view).
  # ../../build.json = src/build.json (vendored by build.sh). Must NOT reach
  # outside src/ — a path: flake escaping src/ copies the whole repo (proot dies).
  buildJson = builtins.fromJSON (builtins.readFile ../../build.json);
  wgIp = buildJson.defaults.wg_ip or "127.0.0.1";
  sshPort = buildJson.defaults.ssh_port or 8023;

  # Runtime JSON (fire-rule 4 + 6): wg_ip/ssh_port still originate from
  # build.json above at Nix eval time; only their *consumption* moved from
  # Nix-eval-time interpolation into a runtime jq read in cloud-ide-sshd.sh.
  # Deployed to ${XDG_CONFIG_HOME:-$HOME/.config}/cloud-data/cloud-ide-sshd.json
  sshdRuntimeJson = builtins.toJSON {
    wg_ip = wgIp;
    ssh_port = sshPort;
  };

  sshdPkg = pkgs.writeShellApplication {
    name = "cloud-ide-sshd";
    runtimeInputs = [ pkgs.jq pkgs.iproute2 pkgs.gawk pkgs.gnugrep pkgs.gnused pkgs.procps pkgs.coreutils ];
    runtimeEnv = {
      CLOUD_IDE_SSHD_BIN = "${opensshPinned}/bin/sshd";
      CLOUD_IDE_SSH_KEYGEN_BIN = "${opensshPinned}/bin/ssh-keygen";
    };
    text = builtins.readFile ./cloud-ide-sshd.sh;
  };
  profileText = ''
    # Generated by sshd.nix — required for SSH sessions on nix-on-droid.
    # Without this, /bin/sh sessions have no nix tooling on PATH.
    if [ -r "$HOME/.nix-profile/etc/profile.d/nix-on-droid-session-init.sh" ]; then
      . "$HOME/.nix-profile/etc/profile.d/nix-on-droid-session-init.sh"
    elif [ -r "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
      . "$HOME/.nix-profile/etc/profile.d/nix.sh"
    fi
    [ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
  '';
in
{
  # Pinned OpenSSH 8.9p1 — wrapper interpolates its absolute store path so
  # there's no PATH ambiguity. Also expose it on PATH for ad-hoc use.
  home.packages = [ opensshPinned ];

  # home.activation.installPatchedProot — DISABLED until tzdata-static-musl
  # builds again. See the comment near prootPatched above for context.

  # ── Runtime JSON deploy (Home Manager: xdg.configFile) ─────────────────
  xdg.configFile."cloud-data/cloud-ide-sshd.json".text = sshdRuntimeJson;

  home.file.".local/bin/cloud-ide-sshd".source = "${sshdPkg}/bin/cloud-ide-sshd";

  # authorized_keys is generated at activation: static trusted keys (baked
  # from authorized-keys.json) are ALWAYS written first so a sops failure
  # can never lock us out of WG SSH; the Cloud IDE key is then appended
  # best-effort from the sops-encrypted secrets.yaml.
  home.activation.cloudIdeAuthorizedKeys = lib.hm.dag.entryAfter ["linkGeneration"] ''
    SOPS="$HOME/.nix-profile/bin/sops"
    # Pin the age identity to the on-device XDG path. An ambient SOPS_AGE_KEY_FILE
    # may point at the desktop vault path (/home/diego/...) which doesn't exist
    # here, silently breaking decrypt. |: true keeps this safe under set -e.
    [ -r "$HOME/.config/sops/age/keys.txt" ] && export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt" || true
    YQ="${pkgs.yq-go}/bin/yq"
    SECRETS="${secretsFile}"
    OUT="$HOME/.ssh/authorized_keys"
    mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh"
    # Old generations symlinked this into the read-only nix store — drop it
    # before writing a real file.
    rm -f "$OUT"
    printf '%s' ${lib.escapeShellArg authorizedKeysContent} > "$OUT"
    if [ -f "$SOPS" ] && [ -f "$SECRETS" ]; then
      _key=$("$SOPS" -d "$SECRETS" 2>/dev/null | "$YQ" -r '.cloud_ide_authorized_keys' 2>/dev/null) || true
      if [ -n "$_key" ] && [ "$_key" != "null" ]; then
        printf '%s\n' "$_key" >> "$OUT"
        echo "[cloud-ide-sshd] authorized_keys: static keys + cloud-ide key"
      else
        echo "[cloud-ide-sshd] WARNING: cloud-ide key decrypt failed — static keys only"
      fi
    fi
    chmod 600 "$OUT"
  '';

  # ~/.profile loads nix env for ssh-spawned /bin/sh sessions
  home.file.".profile".text = profileText;

  programs.fish.shellInit = lib.mkAfter ''
    if not test -f $HOME/.cache/sshd.pid; or not kill -0 (cat $HOME/.cache/sshd.pid 2>/dev/null) 2>/dev/null
      cloud-ide-sshd start >/dev/null 2>&1
    end
  '';
}
