#!/usr/bin/env bash
# waydroid-apps — declarative Android app provisioning for the local Waydroid container.
#
# Everything is data-driven from build.json. The engine NEVER hardcodes the package
# list, the dock order, F-Droid endpoints, the Waydroid data root, or the launcher DB
# schema — packages/order come from build.json, hashes from src/apps.lock.json, and the
# launcher favorites schema is introspected live before any write.
#
# Pipeline:
#   ./build.sh lock      # resolve F-Droid suggestedVersionCode + nix-prefetch sha256 -> src/apps.lock.json
#   ./build.sh build     # nix build the pinned APK set -> dist/apks/ (+ copy local-built apps)
#   ./build.sh check     # verify lockfile <-> build.json, and that every APK is present
#   ./build.sh install   # waydroid app install every APK (requires a RUNNING session)
#   ./build.sh dock      # seed the launcher hotseat from dock_order (requires RUNNING session)
#   ./build.sh undock    # restore the most recent launcher.db backup
#   ./build.sh status    # show session + what's installed + current hotseat
#   ./build.sh ship      # lock(if missing) + build + install + dock
#   ./build.sh clean     # rm dist/
#   (default = build)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$ROOT/build.json"
SRC="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.src)")"
DIST="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.dist)")"
APK_DIR="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.apk_dir)")"
LOCKFILE="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.lockfile)")"
BACKUP_DIR="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.backup_dir)")"

c_g='\033[0;32m'; c_y='\033[0;33m'; c_r='\033[0;31m'; c_0='\033[0m'
log()  { printf "${c_g}[waydroid-apps]${c_0} %s\n" "$*"; }
warn() { printf "${c_y}[waydroid-apps]${c_0} %s\n" "$*"; }
die()  { printf "${c_r}[waydroid-apps] ERROR:${c_0} %s\n" "$*" >&2; exit 1; }

get()      { node -e "const c=require('$CONFIG');const v='$1'.split('.').reduce((o,k)=>o&&o[k],c);process.stdout.write(String(v??''))"; }
get_json() { node -e "const c=require('$CONFIG');const v='$1'.split('.').reduce((o,k)=>o&&o[k],c);process.stdout.write(JSON.stringify(v??null))"; }

# ── Waydroid host discovery (no hardcoded paths) ────────────────────────────
wd_data_root() {
  local r
  while read -r r; do
    [ -n "$r" ] && [ -d "$r" ] && { printf '%s' "$r"; return 0; }
  done < <(node -e "require('$CONFIG').waydroid.data_roots.forEach(r=>console.log(r))")
  die "no Waydroid data root found (checked waydroid.data_roots in build.json)"
}
wd_db() {
  local root glob db
  root="$(wd_data_root)"
  glob="$(get waydroid.launcher_db_glob)"
  # grid-dependent filename (launcher_<cols>_by_<rows>.db) -> glob, never assume
  db="$(sudo find "$root" -path "$root/$glob" 2>/dev/null | sort | head -1)"
  [ -n "$db" ] || die "launcher DB not found under $root/$glob"
  printf '%s' "$db"
}
session_running() { waydroid status 2>/dev/null | grep -q 'Session:.*RUNNING'; }
require_session() {
  session_running || die "Waydroid session is not RUNNING. Start it in your Wayland session: 'waydroid session start' (or your launcher), then re-run."
}

# ── lock: resolve pinned versions + hashes from F-Droid ─────────────────────
cmd_lock() {
  local api repo
  api="$(get fdroid.api_url)"; repo="$(get fdroid.repo_url)"
  log "Resolving F-Droid versions + hashes (this fetches each APK once to pin its sha256)…"
  local tmp; tmp="$(mktemp)"
  echo '{"_doc":"GENERATED by build.sh lock — do not edit by hand. Re-run lock to refresh.","generated_for":"waydroid-apps","apps":[]}' > "$tmp"

  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg stype
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    stype="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.type)")"
    case "$stype" in
      fdroid)
        local vc url pref
        vc="$(curl -fsSL "$api/$pkg" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(String(JSON.parse(d).suggestedVersionCode)))')"
        [ -n "$vc" ] && [ "$vc" != "undefined" ] || die "could not resolve suggestedVersionCode for $pkg"
        url="$repo/${pkg}_${vc}.apk"
        log "  $pkg -> versionCode $vc ; prefetching…"
        pref="$(nix store prefetch-file --json "$url")"
        local sha
        sha="$(printf '%s' "$pref" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(JSON.parse(d).hash))')"
        node -e "
          const fs=require('fs');const f='$tmp';const o=JSON.parse(fs.readFileSync(f));
          o.apps.push({package:'$pkg',source:'fdroid',versionCode:$vc,url:'$url',sha256:'$sha'});
          fs.writeFileSync(f,JSON.stringify(o,null,2));"
        ;;
      github)
        local url sha
        url="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.url||'')")"
        [ -n "$url" ] || die "github source for $pkg has no url in build.json"
        log "  $pkg -> github ; prefetching…"
        sha="$(nix store prefetch-file --json "$url" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(JSON.parse(d).hash))')"
        node -e "
          const fs=require('fs');const f='$tmp';const o=JSON.parse(fs.readFileSync(f));
          o.apps.push({package:'$pkg',source:'github',url:'$url',sha256:'$sha'});
          fs.writeFileSync(f,JSON.stringify(o,null,2));"
        ;;
      local)
        log "  $pkg -> local build (not locked; built by build.sh build)"
        ;;
      *) die "unknown source.type '$stype' for $pkg" ;;
    esac
  done
  mkdir -p "$(dirname "$LOCKFILE")"
  mv "$tmp" "$LOCKFILE"
  log "Lockfile written: $LOCKFILE"
}

# ── build: fetch pinned APKs via nix + copy local-built APKs ────────────────
cmd_build() {
  [ -f "$LOCKFILE" ] || { warn "no lockfile; running lock first"; cmd_lock; }
  rm -rf "$APK_DIR"; mkdir -p "$APK_DIR"
  log "nix build of pinned APK set…"
  mkdir -p "$DIST"
  # path: flake (src/ is a subdir of the unix git repo) — includes not-yet-committed
  # files; reproducibility is guaranteed by the pinned hashes in src/apps.lock.json.
  nix build "path:$SRC#apks" --no-link --print-out-paths > "$DIST/.apks.out"
  local out; out="$(cat "$DIST/.apks.out")"
  cp -f "$out"/apks/*.apk "$APK_DIR"/
  log "Fetched $(ls "$APK_DIR" | wc -l) pinned APK(s) into dist/apks/"

  # local-source apps (e.g. cloud-superapp x86_64)
  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i
  for ((i=0;i<n;i++)); do
    local stype pkg
    stype="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.type)")"
    [ "$stype" = "local" ] || continue
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    local proj glob varenv varval found
    proj="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_project)")"
    glob="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.apk_glob)")"
    varenv="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_variant_env||'')")"
    varval="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_variant||'')")"
    found="$(ls "$ROOT/$proj"/$glob 2>/dev/null | head -1 || true)"
    if [ -z "$found" ]; then
      warn "local app $pkg: no prebuilt APK at $proj/$glob."
      warn "  Build it with: ( cd $proj && ${varenv:+$varenv=$varval }./build.sh build )  then re-run."
      continue
    fi
    cp -f "$found" "$APK_DIR/$pkg.apk"
    log "  local $pkg -> $(basename "$found")"
  done
}

cmd_nix() { nix build "path:$SRC#apks" --print-out-paths; }

# ── check: lockfile <-> build.json + APK presence ───────────────────────────
cmd_check() {
  [ -f "$LOCKFILE" ] || die "no lockfile — run: ./build.sh lock"
  node -e "
    const cfg=require('$CONFIG'), lock=require('$LOCKFILE');
    const want=cfg.apps.filter(a=>a.source.type==='fdroid'||a.source.type==='github').map(a=>a.package).sort();
    const have=lock.apps.map(a=>a.package).sort();
    const miss=want.filter(p=>!have.includes(p)), extra=have.filter(p=>!want.includes(p));
    if(miss.length||extra.length){console.error('lockfile drift. missing:',miss,'stale:',extra);process.exit(1);}
    console.log('lockfile matches build.json ('+want.length+' remote apps)');
  " || die "lockfile out of sync with build.json — run: ./build.sh lock"
  local n missing=0; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    if [ -f "$APK_DIR/$pkg.apk" ]; then printf '  ✓ %s\n' "$pkg"; else printf "  ${c_r}✗ %s (missing APK)${c_0}\n" "$pkg"; missing=1; fi
  done
  [ "$missing" -eq 0 ] || die "some APKs missing — run: ./build.sh build"
  log "check OK"
}

# ── install: waydroid app install every built APK ───────────────────────────
cmd_install() {
  require_session
  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    [ -f "$APK_DIR/$pkg.apk" ] || { warn "skip $pkg (no APK; run build)"; continue; }
    log "installing $pkg…"
    waydroid app install "$APK_DIR/$pkg.apk" || warn "install reported an error for $pkg (may already be installed)"
  done
  log "install pass complete"
}

# ── dock: seed the launcher hotseat from dock_order (schema-introspecting) ───
resolve_component() {
  # data-driven: ask the framework for the package's LAUNCHER activity
  local pkg="$1" out
  out="$(waydroid shell cmd package resolve-activity --brief -c android.intent.category.LAUNCHER "$pkg" 2>/dev/null || true)"
  out="${out//$'\r'/}"
  # last non-empty line is "<pkg>/<activity>"
  printf '%s' "$out" | awk 'NF{l=$0} END{print l}'
}

cmd_dock() {
  require_session
  local db; db="$(wd_db)"
  local container item_type flags
  container="$(get waydroid.hotseat_container)"
  item_type="$(get waydroid.item_type_application)"
  flags="$(get waydroid.launch_flags)"
  log "launcher DB: $db"

  # detect hotseat slot count from the live grid (current max screen+1, min 4)
  local slots
  slots="$(sudo sqlite3 "$db" "SELECT max(screen)+1 FROM favorites WHERE container=$container;" 2>/dev/null || echo 0)"
  [ -n "$slots" ] && [ "$slots" -ge 1 ] 2>/dev/null || slots=6
  log "hotseat slots detected: $slots"

  # build ordered (dock_order, package, label) list, resolve components live
  local rows_json="[]"
  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i
  declare -a ORDER PKGS LABELS COMPS
  for ((i=0;i<n;i++)); do
    local d; d="$(node -e "const a=require('$CONFIG').apps[$i];process.stdout.write(a.dock_order===null||a.dock_order===undefined?'':String(a.dock_order))")"
    [ -n "$d" ] || continue
    local pkg label comp
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    label="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].label)")"
    comp="$(resolve_component "$pkg")"
    if [ -z "$comp" ] || [[ "$comp" != "$pkg/"* && "$comp" != *"/"* ]]; then
      warn "could not resolve launcher activity for $pkg — is it installed? skipping in dock."
      continue
    fi
    ORDER+=("$d"); PKGS+=("$pkg"); LABELS+=("$label"); COMPS+=("$comp")
  done
  [ "${#PKGS[@]}" -gt 0 ] || die "no installable dock apps resolved — run install first"

  # backup
  mkdir -p "$BACKUP_DIR"
  local ts bak; ts="$(node -e "process.stdout.write(String(Date.now()))")"
  bak="$BACKUP_DIR/launcher.db.$ts.bak"
  sudo cp -f "$db" "$bak"; sudo chown "$USER" "$bak" 2>/dev/null || true
  log "backed up launcher.db -> $bak"

  # generate SQL with proper escaping via node
  local sqlfile="$DIST/dock.sql"
  ORDER_J="$(printf '%s\n' "${ORDER[@]}" | node -e 'let a=require("fs").readFileSync(0,"utf8").trim().split("\n");process.stdout.write(JSON.stringify(a))')"
  PKGS_J="$(printf '%s\n' "${PKGS[@]}" | node -e 'let a=require("fs").readFileSync(0,"utf8").trim().split("\n");process.stdout.write(JSON.stringify(a))')"
  LABELS_J="$(printf '%s\n' "${LABELS[@]}" | node -e 'let a=require("fs").readFileSync(0,"utf8").trim().split("\n");process.stdout.write(JSON.stringify(a))')"
  COMPS_J="$(printf '%s\n' "${COMPS[@]}" | node -e 'let a=require("fs").readFileSync(0,"utf8").trim().split("\n");process.stdout.write(JSON.stringify(a))')"

  CONTAINER="$container" ITEM_TYPE="$item_type" FLAGS="$flags" SLOTS="$slots" \
  ORDER_J="$ORDER_J" PKGS_J="$PKGS_J" LABELS_J="$LABELS_J" COMPS_J="$COMPS_J" \
  node "$SRC/lib/gen-dock-sql.js" > "$sqlfile"

  log "generated $sqlfile:"; sed 's/^/    /' "$sqlfile"

  # apply with launcher stopped (avoid WAL races), then relaunch
  log "stopping launcher, applying, relaunching…"
  waydroid shell am force-stop "$(get waydroid.launcher_package)" 2>/dev/null || true
  sudo sqlite3 "$db" < "$sqlfile" || { warn "sqlite apply failed — restoring backup"; sudo cp -f "$bak" "$db"; die "dock aborted, backup restored"; }
  # checkpoint any WAL so the running launcher sees it
  sudo sqlite3 "$db" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null 2>&1 || true
  waydroid shell am start -n "$(get waydroid.launcher_package)/.uioverrides.QuickstepLauncher" >/dev/null 2>&1 \
    || waydroid shell monkey -p "$(get waydroid.launcher_package)" 1 >/dev/null 2>&1 || true

  # verify
  local got; got="$(sudo sqlite3 "$db" "SELECT count(*) FROM favorites WHERE container=$container;")"
  log "hotseat now has $got entries:"
  sudo sqlite3 -header -column "$db" "SELECT screen,title FROM favorites WHERE container=$container ORDER BY screen;" | sed 's/^/    /'
  log "dock seeded. (Backup: $bak — restore with: ./build.sh undock)"
}

cmd_undock() {
  local db bak; db="$(wd_db)"
  bak="$(ls -t "$BACKUP_DIR"/launcher.db.*.bak 2>/dev/null | head -1 || true)"
  [ -n "$bak" ] || die "no backup found in $BACKUP_DIR"
  waydroid shell am force-stop "$(get waydroid.launcher_package)" 2>/dev/null || true
  sudo cp -f "$bak" "$db"
  sudo sqlite3 "$db" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null 2>&1 || true
  log "restored $db from $bak"
}

cmd_status() {
  printf "Session: "; waydroid status 2>/dev/null | grep -E 'Session:|Container:' || echo "unknown"
  echo "--- declared apps (build.json) ---"
  node -e "require('$CONFIG').apps.forEach(a=>console.log('  '+(a.dock_order??'-')+'  ['+a.group+']  '+a.package+'  ('+a.label+')'))"
  echo "--- built APKs (dist/apks) ---"; ls "$APK_DIR" 2>/dev/null | sed 's/^/  /' || echo "  (none — run build)"
  if session_running; then
    echo "--- live hotseat ---"
    local db; db="$(wd_db)"
    sudo sqlite3 -column "$db" "SELECT screen,title FROM favorites WHERE container=$(get waydroid.hotseat_container) ORDER BY screen;" 2>/dev/null | sed 's/^/  /'
  fi
}

cmd_ship() { [ -f "$LOCKFILE" ] || cmd_lock; cmd_build; cmd_install; cmd_dock; }
cmd_clean() { rm -rf "$DIST"; log "cleaned dist/"; }

case "${1:-build}" in
  lock) cmd_lock ;;
  build) cmd_build ;;
  nix) cmd_nix ;;
  check) cmd_check ;;
  install) cmd_install ;;
  dock) cmd_dock ;;
  undock) cmd_undock ;;
  status) cmd_status ;;
  ship) cmd_ship ;;
  clean) cmd_clean ;;
  *) die "unknown command '$1' (lock|build|nix|check|install|dock|undock|status|ship|clean)" ;;
esac
