#!/usr/bin/env bash
# waydroid-apps — declarative Android app provisioning for the local Waydroid container.
#
# Everything is data-driven from build.json. The engine NEVER hardcodes the package
# list, the dock order, F-Droid endpoints, the Waydroid data root, or the launcher DB
# schema — packages/order come from build.json, hashes from src/apps.lock.json, and the
# launcher favorites schema is introspected live before any write.
#
# Pipeline:
#   ./build.sh lock      # resolve F-Droid suggestedVersionCode + nix-prefetch sha256 -> src/apps.lock.json
#   ./build.sh build     # nix build the pinned APK set -> dist/apks/ (+ copy local-built apps)
#   ./build.sh check     # verify lockfile <-> build.json, and that every APK is present
#   ./build.sh install   # waydroid app install every APK (requires a RUNNING session)
#   ./build.sh layout    # render folders+hotseat+workspace into Launcher3 DB (needs session)
#   ./build.sh theme     # dark mode + generated dark wallpaper (needs session)
#   ./build.sh undock    # restore the most recent launcher.db backup
#   ./build.sh status    # show session + what's installed + current hotseat
#   ./build.sh ship      # lock(if missing) + build + install + dock
#   ./build.sh clean     # rm dist/
#   (default = build)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$ROOT/build.json"
SRC="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.src)")"
DIST="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.dist)")"
APK_DIR="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.apk_dir)")"
LOCKFILE="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.lockfile)")"
BACKUP_DIR="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.backup_dir)")"
WALLPAPER="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.wallpaper)")"

c_g='\033[0;32m'; c_y='\033[0;33m'; c_r='\033[0;31m'; c_0='\033[0m'
log()  { printf "${c_g}[waydroid-apps]${c_0} %s\n" "$*"; }
warn() { printf "${c_y}[waydroid-apps]${c_0} %s\n" "$*"; }
die()  { printf "${c_r}[waydroid-apps] ERROR:${c_0} %s\n" "$*" >&2; exit 1; }

get()      { node -e "const c=require('$CONFIG');const v='$1'.split('.').reduce((o,k)=>o&&o[k],c);process.stdout.write(String(v??''))"; }
get_json() { node -e "const c=require('$CONFIG');const v='$1'.split('.').reduce((o,k)=>o&&o[k],c);process.stdout.write(JSON.stringify(v??null))"; }

# ── Waydroid host discovery (no hardcoded paths) ────────────────────────────
wd_data_root() {
  local r
  while read -r r; do
    [ -n "$r" ] && [ -d "$r" ] && { printf '%s' "$r"; return 0; }
  done < <(node -e "require('$CONFIG').waydroid.data_roots.forEach(r=>console.log(r))")
  die "no Waydroid data root found (checked waydroid.data_roots in build.json)"
}
wd_db() {
  local root glob db
  root="$(wd_data_root)"
  glob="$(get waydroid.launcher_db_glob)"
  # grid-dependent filename (launcher_<cols>_by_<rows>.db) -> glob, never assume
  db="$(sudo find "$root" -path "$root/$glob" 2>/dev/null | sort | head -1)"
  [ -n "$db" ] || die "launcher DB not found under $root/$glob"
  printf '%s' "$db"
}
session_running() { waydroid status 2>/dev/null | grep -q 'Session:.*RUNNING'; }
require_session() {
  session_running || die "Waydroid session is not RUNNING. Start it in your Wayland session: 'waydroid session start' (or your launcher), then re-run."
}

# Container ops (`shell`, `app install`) require root on most setups. Detect rather
# than hardcode: if `waydroid shell` works unprivileged use it, else elevate.
WDSH=( waydroid )
detect_priv() {
  if waydroid shell -- true >/dev/null 2>&1; then WDSH=( waydroid )
  else WDSH=( sudo waydroid ); fi
}
# `--` stops waydroid's own argparse so flags (-c, -n, -p, --brief) reach the Android shell.
wd_shell() { "${WDSH[@]}" shell -- "$@"; }

# The sqlite3 CLI is NOT on the host PATH (NixOS ships it only via a package),
# and `sudo` sanitizes PATH anyway — so a bare `sudo sqlite3` dies with
# "command not found". Resolve it REPRODUCIBLY from nixpkgs (same pattern as
# cmd_wallpaper's imagemagick) and hand sudo the absolute store path. Callers
# capture it once into a local (e.g. `SQ="$(wd_sqlite3)"`) then `sudo "$SQ" …`.
wd_sqlite3() {
  local b
  b="$(nix build --no-link --print-out-paths nixpkgs#sqlite-interactive 2>/dev/null | head -1)/bin/sqlite3"
  [ -x "$b" ] || die "could not resolve sqlite3 via nixpkgs#sqlite-interactive"
  printf '%s' "$b"
}

# ── lock: resolve pinned versions + hashes from F-Droid ─────────────────────
cmd_lock() {
  local api repo
  api="$(get fdroid.api_url)"; repo="$(get fdroid.repo_url)"
  log "Resolving F-Droid versions + hashes (this fetches each APK once to pin its sha256)…"
  local tmp; tmp="$(mktemp)"
  echo '{"_doc":"GENERATED by build.sh lock — do not edit by hand. Re-run lock to refresh.","generated_for":"waydroid-apps","apps":[]}' > "$tmp"

  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg stype
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    stype="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.type)")"
    case "$stype" in
      fdroid)
        local vc url pref
        vc="$(curl -fsSL "$api/$pkg" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(String(JSON.parse(d).suggestedVersionCode)))')"
        [ -n "$vc" ] && [ "$vc" != "undefined" ] || die "could not resolve suggestedVersionCode for $pkg"
        url="$repo/${pkg}_${vc}.apk"
        log "  $pkg -> versionCode $vc ; prefetching…"
        pref="$(nix store prefetch-file --json "$url")"
        local sha
        sha="$(printf '%s' "$pref" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(JSON.parse(d).hash))')"
        node -e "
          const fs=require('fs');const f='$tmp';const o=JSON.parse(fs.readFileSync(f));
          o.apps.push({package:'$pkg',source:'fdroid',versionCode:$vc,url:'$url',sha256:'$sha'});
          fs.writeFileSync(f,JSON.stringify(o,null,2));"
        ;;
      github)
        local url sha
        url="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.url||'')")"
        [ -n "$url" ] || die "github source for $pkg has no url in build.json"
        log "  $pkg -> github ; prefetching…"
        sha="$(nix store prefetch-file --json "$url" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>process.stdout.write(JSON.parse(d).hash))')"
        node -e "
          const fs=require('fs');const f='$tmp';const o=JSON.parse(fs.readFileSync(f));
          o.apps.push({package:'$pkg',source:'github',url:'$url',sha256:'$sha'});
          fs.writeFileSync(f,JSON.stringify(o,null,2));"
        ;;
      local)
        log "  $pkg -> local build (not locked; built by build.sh build)"
        ;;
      *) die "unknown source.type '$stype' for $pkg" ;;
    esac
  done
  mkdir -p "$(dirname "$LOCKFILE")"
  mv "$tmp" "$LOCKFILE"
  log "Lockfile written: $LOCKFILE"
}

# ── build: fetch pinned APKs via nix + copy local-built APKs ────────────────
cmd_build() {
  [ -f "$LOCKFILE" ] || { warn "no lockfile; running lock first"; cmd_lock; }
  rm -rf "$APK_DIR"; mkdir -p "$APK_DIR"
  log "nix build of pinned APK set…"
  mkdir -p "$DIST"
  # path: flake (src/ is a subdir of the unix git repo) — includes not-yet-committed
  # files; reproducibility is guaranteed by the pinned hashes in src/apps.lock.json.
  nix build "path:$SRC#apks" --no-link --print-out-paths > "$DIST/.apks.out"
  local out; out="$(cat "$DIST/.apks.out")"
  cp -f "$out"/apks/*.apk "$APK_DIR"/
  log "Fetched $(ls "$APK_DIR" | wc -l) pinned APK(s) into dist/apks/"

  # local-source apps (e.g. cloud-superapp x86_64)
  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i
  for ((i=0;i<n;i++)); do
    local stype pkg
    stype="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.type)")"
    [ "$stype" = "local" ] || continue
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    local proj glob varenv varval found
    proj="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_project)")"
    glob="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.apk_glob)")"
    varenv="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_variant_env||'')")"
    varval="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].source.build_variant||'')")"
    found="$(ls "$ROOT/$proj"/$glob 2>/dev/null | head -1 || true)"
    if [ -z "$found" ]; then
      warn "local app $pkg: no prebuilt APK at $proj/$glob."
      warn "  Build it with: ( cd $proj && ${varenv:+$varenv=$varval }./build.sh build )  then re-run."
      continue
    fi
    cp -f "$found" "$APK_DIR/$pkg.apk"
    log "  local $pkg -> $(basename "$found")"
  done
}

cmd_nix() { nix build "path:$SRC#apks" --print-out-paths; }

# ── check: lockfile <-> build.json + APK presence ───────────────────────────
cmd_check() {
  [ -f "$LOCKFILE" ] || die "no lockfile — run: ./build.sh lock"
  node -e "
    const cfg=require('$CONFIG'), lock=require('$LOCKFILE');
    const want=cfg.apps.filter(a=>a.source.type==='fdroid'||a.source.type==='github').map(a=>a.package).sort();
    const have=lock.apps.map(a=>a.package).sort();
    const miss=want.filter(p=>!have.includes(p)), extra=have.filter(p=>!want.includes(p));
    if(miss.length||extra.length){console.error('lockfile drift. missing:',miss,'stale:',extra);process.exit(1);}
    console.log('lockfile matches build.json ('+want.length+' remote apps)');
  " || die "lockfile out of sync with build.json — run: ./build.sh lock"
  local n missing=0; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    if [ -f "$APK_DIR/$pkg.apk" ]; then printf '  ✓ %s\n' "$pkg"; else printf "  ${c_r}✗ %s (missing APK)${c_0}\n" "$pkg"; missing=1; fi
  done
  [ "$missing" -eq 0 ] || die "some APKs missing — run: ./build.sh build"
  log "check OK"
}

# ── install: stage APK into the container + `pm install` (robust) ───────────
# `waydroid app install` silently no-ops for some APKs (esp. larger ones), so we
# push the APK into the container's tmp and use pm install -r -d directly.
cmd_install() {
  require_session; detect_priv
  local ctmp host_tmp; ctmp="$(get waydroid.container_tmp)"; host_tmp="$(wd_data_root)/local/tmp"
  sudo mkdir -p "$host_tmp"
  # Data-driven: -g auto-grants all declared runtime permissions at install (no prompts).
  local grantflag=""; [ "$(get waydroid.grant_all_permissions)" = "true" ] && grantflag="-g"
  local n; n="$(node -e "process.stdout.write(String(require('$CONFIG').apps.length))")"
  local i pkg
  for ((i=0;i<n;i++)); do
    pkg="$(node -e "process.stdout.write(require('$CONFIG').apps[$i].package)")"
    [ -f "$APK_DIR/$pkg.apk" ] || { warn "skip $pkg (no APK; run build)"; continue; }
    log "installing $pkg…"
    sudo cp -f "$APK_DIR/$pkg.apk" "$host_tmp/$pkg.apk"
    local out; out="$(wd_shell pm install -r -d $grantflag "$ctmp/$pkg.apk" 2>&1)"; out="${out//$'\r'/}"
    if [[ "$out" != *Success* ]]; then
      # Signing-key change (e.g. debug→release, or the shared constellation key): pm
      # install -r can't replace a different signature → uninstall the old one, then
      # install fresh. (Loses that app's data.) Covers all signature-mismatch verdicts.
      if [[ "$out" == *"signatures do not match"* || "$out" == *UPDATE_INCOMPATIBLE* || "$out" == *INCONSISTENT_CERTIFICATES* || "$out" == *"signature"* ]]; then
        warn "  $pkg signing key changed → uninstall + reinstall"
        wd_shell pm uninstall "$pkg" >/dev/null 2>&1 || true
        out="$(wd_shell pm install -d $grantflag "$ctmp/$pkg.apk" 2>&1)"; out="${out//$'\r'/}"
      fi
      [[ "$out" == *Success* ]] || warn "  pm install issue for $pkg: ${out##*$'\n'}"
    fi
    sudo rm -f "$host_tmp/$pkg.apk"
    # verify it actually landed
    if wd_shell pm path "$pkg" >/dev/null 2>&1; then log "  ✓ $pkg present"; else warn "  ✗ $pkg NOT present after install"; fi
  done
  log "install pass complete"
}

# ── layout: render the data-driven launcher layout (folders+hotseat+workspace) ──
resolve_component() {
  # data-driven: ask the framework for the package's LAUNCHER activity
  local pkg="$1" out
  out="$(wd_shell cmd package resolve-activity --brief -c android.intent.category.LAUNCHER "$pkg" 2>/dev/null || true)"
  out="${out//$'\r'/}"
  printf '%s' "$out" | awk 'NF{l=$0} END{print l}'   # last non-empty line = "<pkg>/<activity>"
}

cmd_layout() {
  require_session; detect_priv
  local db; db="$(wd_db)"
  local SQ; SQ="$(wd_sqlite3)"
  log "launcher DB: $db"

  # unique package set referenced anywhere in launcher{} (folders + hotseat + workspace)
  local pkgs; pkgs="$(node -e "
    const l=require('$CONFIG').launcher; const s=new Set();
    // skip '_'-prefixed doc keys (data-driven _doc convention) + any non-folder value
    Object.entries(l.folders).forEach(([k,f])=>{ if(k.startsWith('_')||!f||!Array.isArray(f.members)) return; f.members.forEach(m=>s.add(m)); });
    l.hotseat.forEach(r=>{ if(!String(r).startsWith('folder:')) s.add(r); });
    l.workspace.cells.forEach(c=>{ if(!String(c.ref).startsWith('folder:')) s.add(c.ref); });
    console.log([...s].join('\n'));
  ")"

  # resolve each package's launcher component live -> COMPONENTS_J map
  local compfile="$DIST/.components.tsv"; : > "$compfile"
  local pkg comp
  while read -r pkg; do
    [ -n "$pkg" ] || continue
    comp="$(resolve_component "$pkg")"
    if [ -z "$comp" ] || [[ "$comp" != *"/"* ]]; then warn "unresolved (installed?): $pkg"; continue; fi
    printf '%s\t%s\n' "$pkg" "$comp" >> "$compfile"
  done <<< "$pkgs"
  local COMPONENTS_J; COMPONENTS_J="$(node -e "
    const fs=require('fs');const m={};
    for(const l of fs.readFileSync('$compfile','utf8').split('\n')){ if(!l.trim())continue; const [p,c]=l.split('\t'); m[p]=c; }
    process.stdout.write(JSON.stringify(m));
  ")"

  # backup
  mkdir -p "$BACKUP_DIR"
  local ts bak; ts="$(node -e "process.stdout.write(String(Date.now()))")"
  bak="$BACKUP_DIR/launcher.db.$ts.bak"
  sudo cp -f "$db" "$bak"; sudo chown "$USER" "$bak" 2>/dev/null || true
  log "backed up launcher.db -> $bak"

  # generate the full layout SQL from build.json launcher{}
  local sqlfile="$DIST/layout.sql"
  FOLDERS_J="$(node -e "process.stdout.write(JSON.stringify(require('$CONFIG').launcher.folders))")" \
  HOTSEAT_J="$(node -e "process.stdout.write(JSON.stringify(require('$CONFIG').launcher.hotseat))")" \
  WORKSPACE_J="$(node -e "process.stdout.write(JSON.stringify(require('$CONFIG').launcher.workspace))")" \
  COMPONENTS_J="$COMPONENTS_J" \
  HOTSEAT_CONTAINER="$(get waydroid.hotseat_container)" \
  WORKSPACE_CONTAINER="$(get waydroid.workspace_container)" \
  FLAGS="$(get waydroid.launch_flags)" \
  ITEM_APP="$(get waydroid.item_type_application)" \
  ITEM_FOLDER="$(get waydroid.item_type_folder)" \
  node "$SRC/lib/gen-layout-sql.js" > "$sqlfile"
  log "generated $sqlfile ($(grep -c '^INSERT' "$sqlfile") rows)"

  # apply with launcher stopped, then relaunch.
  # CRITICAL: sqlite3 runs as root, so the db + its -wal/-shm sidecars become
  # root-owned. Launcher3 (its own app uid) then can't open them and crash-loops
  # ("SQLiteCantOpenDatabaseException: ... databases doesn't exist"). We capture
  # the db's Android owner BEFORE writing and restore it AFTER, and drop the
  # stale WAL/SHM so Launcher3 recreates them as itself. This is what makes
  # launcher.db seeding safe (previously it permanently broke the launcher).
  local dbowner; dbowner="$(sudo stat -c '%u:%g' "$db")"
  log "stopping launcher, applying layout (restoring db owner $dbowner), relaunching…"
  wd_shell am force-stop "$(get waydroid.launcher_package)" 2>/dev/null || true
  sudo "$SQ" "$db" < "$sqlfile" || { warn "sqlite apply failed — restoring backup"; sudo cp -f "$bak" "$db"; sudo chown "$dbowner" "$db"; die "layout aborted, backup restored"; }
  sudo "$SQ" "$db" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null 2>&1 || true
  sudo rm -f "$db-wal" "$db-shm"
  sudo chown "$dbowner" "$db"
  wd_shell monkey -p "$(get waydroid.launcher_package)" 1 >/dev/null 2>&1 || true

  # verify
  log "hotseat:"
  sudo "$SQ" -column "$db" "SELECT screen,title,itemType FROM favorites WHERE container=$(get waydroid.hotseat_container) ORDER BY screen;" | sed 's/^/    /'
  log "home screen (workspace):"
  sudo "$SQ" -column "$db" "SELECT cellY,cellX,title,itemType FROM favorites WHERE container=$(get waydroid.workspace_container) ORDER BY cellY,cellX;" | sed 's/^/    /'
  log "layout applied. (Backup: $bak — restore with: ./build.sh undock)"
}

# ── theme: dark mode + generated dark wallpaper (data-driven) ───────────────
cmd_wallpaper() {
  local size from to; size="$(get theme.wallpaper.size)"; from="$(get theme.wallpaper.gradient_from)"; to="$(get theme.wallpaper.gradient_to)"
  mkdir -p "$(dirname "$WALLPAPER")"
  log "generating dark wallpaper ($size, $from→$to) via imagemagick…"
  # reproducible: imagemagick pulled from nixpkgs on demand (no host dependency)
  nix shell nixpkgs#imagemagick -c magick -size "$size" "gradient:$from-$to" "$WALLPAPER" \
    || die "wallpaper generation failed (imagemagick)"
  log "wrote $WALLPAPER"
}

cmd_theme() {
  require_session; detect_priv
  # 1) dark mode (Android night UI) — data-driven toggle
  if [ "$(get theme.dark_mode)" = "true" ]; then
    log "enabling dark mode (night UI)…"
    wd_shell cmd uimode night yes >/dev/null 2>&1 || true
    wd_shell settings put secure ui_night_mode 2 >/dev/null 2>&1 || true
  fi
  # 1b) auto-rotate — follow the accelerometer HAL (da_waydroid-sensors)
  if [ "$(get theme.auto_rotate)" = "true" ]; then
    log "enabling auto-rotate (accelerometer_rotation=1)…"
    wd_shell settings put system accelerometer_rotation 1 >/dev/null 2>&1 || true
  fi
  # 2) wallpaper dim — AOSP 13's `cmd wallpaper` has NO set-image subcommand (only
  #    dim controls), so we can't push a generated image from the host. To get the
  #    requested solid-black background we dim the wallpaper to theme.wallpaper.dim
  #    (1.0 = fully black). Data-driven; works on this image (verified subcommands).
  local dim; dim="$(get theme.wallpaper.dim)"
  if [ -n "$dim" ]; then
    log "setting wallpaper dim to $dim (1.0 = solid black)…"
    wd_shell cmd wallpaper set-dim-amount "$dim" >/dev/null 2>&1 \
      || warn "cmd wallpaper set-dim-amount failed"
    log "wallpaper dim set to $dim"
  fi
}

cmd_undock() {
  detect_priv
  local db bak; db="$(wd_db)"
  local SQ; SQ="$(wd_sqlite3)"
  bak="$(ls -t "$BACKUP_DIR"/launcher.db.*.bak 2>/dev/null | head -1 || true)"
  [ -n "$bak" ] || die "no backup found in $BACKUP_DIR"
  wd_shell am force-stop "$(get waydroid.launcher_package)" 2>/dev/null || true
  sudo cp -f "$bak" "$db"
  sudo "$SQ" "$db" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null 2>&1 || true
  log "restored $db from $bak"
}

cmd_status() {
  printf "Session: "; waydroid status 2>/dev/null | grep -E 'Session:|Container:' || echo "unknown"
  echo "--- declared apps (build.json) ---"
  node -e "require('$CONFIG').apps.forEach(a=>console.log('  ['+a.group+']  '+a.package+'  ('+a.label+')'))"
  echo "--- built APKs (dist/apks) ---"; ls "$APK_DIR" 2>/dev/null | sed 's/^/  /' || echo "  (none — run build)"
  if session_running; then
    local db; db="$(wd_db)"
    local SQ; SQ="$(wd_sqlite3)"
    echo "--- live hotseat ---"
    sudo "$SQ" -column "$db" "SELECT screen,title,itemType FROM favorites WHERE container=$(get waydroid.hotseat_container) ORDER BY screen;" 2>/dev/null | sed 's/^/  /'
    echo "--- live workspace ---"
    sudo "$SQ" -column "$db" "SELECT cellY,cellX,title,itemType FROM favorites WHERE container=$(get waydroid.workspace_container) ORDER BY cellY,cellX;" 2>/dev/null | sed 's/^/  /'
  fi
}

# `layout` seeds the Launcher3 home screen (dock + folders + workspace) from
# build.json. It is now SAFE in ship/auto-provision: cmd_layout restores the
# launcher db's Android owner after the root sqlite write, so Launcher3 no longer
# crash-loops (it used to be left root-owned → SQLiteCantOpenDatabaseException).
# Order: install (apps must exist for component resolution) → layout → theme.
cmd_ship() { [ -f "$LOCKFILE" ] || cmd_lock; cmd_build; cmd_install; cmd_layout; cmd_theme; }
cmd_clean() { rm -rf "$DIST"; log "cleaned dist/"; }

case "${1:-build}" in
  lock) cmd_lock ;;
  build) cmd_build ;;
  nix) cmd_nix ;;
  check) cmd_check ;;
  install) cmd_install ;;
  layout) cmd_layout ;;
  theme) cmd_theme ;;
  wallpaper) cmd_wallpaper ;;
  undock) cmd_undock ;;
  status) cmd_status ;;
  ship) cmd_ship ;;
  clean) cmd_clean ;;
  *) die "unknown command '$1' (lock|build|nix|check|install|layout|theme|wallpaper|undock|status|ship|clean)" ;;
esac
