{
  description = "GHA CI/CD build environment — reads deps from cloud-data-deps.json";
  # ┌──────────────────────────────────────────────────────────────────┐
  # │ ARCHITECTURE: Two-layer nix store strategy                       │
  # │                                                                  │
  # │ Layer 1 (CACHED): This devShell closure — all unix tools + node  │
  # │   Reads config.json .deps.system for nix package names.         │
  # │   shellHook installs npm packages to ~/.node_modules.            │
  # │                                                                  │
  # │ Layer 2 (EPHEMERAL): Service build outputs (docker-compose.yml)  │
  # │   GC'd after cache restore — always rebuilt fresh.               │
  # └──────────────────────────────────────────────────────────────────┘

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
    # Live config.json from GitHub — always fresh, never stale
    config-json = {
      url = "https://raw.githubusercontent.com/diegonmarcos/cloud/main/config.json";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, config-json }: let
    forAllSystems = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ];

    # Read deps from config.json fetched live from GitHub
    configJson = builtins.fromJSON (builtins.readFile config-json);
    sysDeps = configJson.deps.system;
    buildDeps = configJson.deps.build or {};
    optDeps = configJson.deps.optional;
    nodeDeps = configJson.deps.node.required or [];

    # Map config.json nix package names to actual nixpkgs attributes
    # Handles dotted paths like "nodePackages.typescript"
    resolvePkg = pkgs: nixStr:
      if nixStr == null then null
      else if builtins.match ".*\\..*" nixStr != null then
        let parts = builtins.split "\\." nixStr;
        in pkgs.${builtins.elemAt parts 0}.${builtins.elemAt parts 2}
      else pkgs.${nixStr};

    # Collect all nix packages from system + optional deps
    collectPkgs = pkgs:
      let
        sysPackages = builtins.filter (p: p != null) (
          builtins.attrValues (builtins.mapAttrs (_: v: resolvePkg pkgs (v.nix or null)) sysDeps)
        );
        buildPackages = builtins.filter (p: p != null) (
          builtins.attrValues (builtins.mapAttrs (_: v: resolvePkg pkgs (v.nix or null)) buildDeps)
        );
        optPackages = builtins.filter (p: p != null) (
          builtins.attrValues (builtins.mapAttrs (_: v: resolvePkg pkgs (v.nix or null)) optDeps)
        );
      in sysPackages ++ buildPackages ++ optPackages;

    buildJson = builtins.fromJSON (builtins.readFile ../build.json);
    registry = buildJson.registry;

    # ── Compose template for builder images ─────────────────────────
    mkBuilderCompose = { variant, imageName, nixSystem, platform ? null }: ''
      # ╔══════════════════════════════════════════════════════════════════╗
      # ║ Cloud Builder — ${variant}                                      ║
      # ║ DO NOT EDIT — generated by cb_containers-builders/src/flake.nix ║
      # ║ Rebuild: build.sh build                                         ║
      # ╠══════════════════════════════════════════════════════════════════╣
      # ║ Usage:                                                          ║
      # ║   docker compose -f compose-${variant}.yaml run builder cmd     ║
      # ╚══════════════════════════════════════════════════════════════════╝

      services:
        builder:
          image: ${registry}/${imageName}:latest
          build:
            context: .
            dockerfile: docker/Dockerfile
            network: host
            args:
              NIX_SYSTEM: ${nixSystem}
          container_name: cloud-builder-${variant}
          ${if platform != null then "platform: ${platform}" else ""}
          network_mode: host
          privileged: true
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ''${HOME:-/root}/.ssh:/root/.ssh:ro
            - ''${HOME:-/root}/.config/sops:/root/.config/sops:ro
          working_dir: /workspace
          entrypoint: ["/opt/cloud-builder/entrypoint.sh"]
          environment:
            - TERM=xterm-256color
            - GITHUB_TOKEN=''${GITHUB_TOKEN:-}
            - GITHUB_ACTOR=''${GITHUB_ACTOR:-}
          labels:
            diego.managed-by: "build.sh"
            diego.image.variant: "${variant}"
    '';

  in {
    devShells = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      default = pkgs.mkShell {
        buildInputs = collectPkgs pkgs;

        NODE_MODULES_DIR = "$HOME/.node_modules";

        shellHook = ''
          # ── Install npm packages to shared ~/.node_modules ──
          NM_DIR="$HOME/.node_modules"
          mkdir -p "$NM_DIR"
          export NODE_PATH="$NM_DIR/node_modules"
          export PATH="$NM_DIR/node_modules/.bin:$PATH"

          # Install required node packages (from config.json .deps.node.required)
          PKGS="${builtins.concatStringsSep " " nodeDeps}"
          if [ -n "$PKGS" ]; then
            cd "$NM_DIR"
            NEEDS_INSTALL=false
            for pkg in $PKGS; do
              [ ! -d "node_modules/$pkg" ] && NEEDS_INSTALL=true && break
            done
            if [ "$NEEDS_INSTALL" = "true" ]; then
              npm install --silent $PKGS 2>/dev/null
            fi
            cd - >/dev/null
          fi
        '';
      };
    });

    packages = forAllSystems (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      default = pkgs.runCommand "builders-compose" {} ''
        mkdir -p $out
        # Multi-arch images: native on matching host, QEMU fallback on x86
        cp ${pkgs.writeText "compose-x-deb-nixhm.yaml" (mkBuilderCompose {
          variant = "x-deb-nixhm";
          imageName = "cloud-builder-x-deb-nixhm";
          nixSystem = "x86_64-linux";
          platform = "linux/amd64,linux/arm64";
        })} $out/compose-x-deb-nixhm.yaml

        cp ${pkgs.writeText "compose-apt.yaml" (mkBuilderCompose {
          variant = "apt";
          imageName = "cloud-builder-x-deb-apt";
          nixSystem = "x86_64-linux";
          platform = "linux/amd64,linux/arm64";
        })} $out/compose-apt.yaml

        cp ${pkgs.writeText "compose-forge.yaml" (mkBuilderCompose {
          variant = "forge";
          imageName = "cloud-builder-x-deb-nixhm-forge";
          nixSystem = "x86_64-linux";
          platform = "linux/amd64,linux/arm64";
        })} $out/compose-forge.yaml

        cp ${../build.json} $out/build.json
      '';
    });
  };
}
