# Cloud npm dependencies — merged from cloud-data-deps.json at activation time.
# Generated by C3 API, synced by Dagu to cloud-data/ repo.
{ config, lib, pkgs, ... }:

let
  nodejs = pkgs.nodejs_20;
in {
  options.nodeNpmDeps.cloud = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = {};
    description = "Cloud service npm dependencies (auto-merged from cloud-data-deps.json)";
  };

  # Activation: read cloud-data-deps.json → populate nodeNpmDeps.cloud
  config.home.activation.mergeCloudDeps = lib.hm.dag.entryBefore ["sharedNodeModules"] ''
    CLOUD_DEPS="$HOME/git/cloud/cloud-data/cloud-data-deps.json"
    CLOUD_OUT="$HOME/.node_modules/.cloud-deps-merged.json"

    if [ -f "$CLOUD_DEPS" ]; then
      PATH="${nodejs}/bin:$PATH" ${nodejs}/bin/node -e "
        const fs = require('fs');
        const deps = {};
        try {
          const d = JSON.parse(fs.readFileSync('$CLOUD_DEPS', 'utf8'));
          const take = (obj) => {
            for (const [k, v] of Object.entries(obj || {})) {
              if (!deps[k] || v > deps[k]) deps[k] = v;
            }
          };
          take(d.node?.merged?.dependencies);
          take(d.node?.merged?.devDependencies);
        } catch (e) { console.error('WARN: cloud-deps: ' + e.message); }
        fs.writeFileSync('$CLOUD_OUT', JSON.stringify(deps, null, 2) + '\n');
        console.log('[node-npm-deps-cloud] ' + Object.keys(deps).length + ' cloud deps extracted');
      " || printf "[node-npm-deps-cloud] WARN: merge failed\n"
    else
      printf "[node-npm-deps-cloud] No cloud-data-deps.json found\n"
      echo '{}' > "$CLOUD_OUT" 2>/dev/null || true
    fi
  '';
}
