# Shared ~/.node_modules — single install for all repos
# Resolution chain: system (nix) → ~/.node_modules → repo/node_modules (fallback)
#
# Source of truth: cloud-deps.json + front-deps.json (generated by build.sh deps,
# synced to cloud-data/ and front-data/ by Dagu). This activation reads those files
# at switch time, merges them into a single package.json, and runs npm install.
#
# Fallback: if deps JSON files are missing, uses the static dotfiles/node/package.json.
{ config, lib, pkgs, ... }:

let
  nodejs = pkgs.nodejs_20;
in {
  # Static fallback package.json (used when deps JSONs are unavailable)
  home.file.".node_modules/package.json.fallback".source = ./dotfiles/node/package.json;

  # Set NODE_PATH so all tools resolve from shared dir
  home.sessionVariables.NODE_PATH = "$HOME/.node_modules/node_modules";

  # Add .bin to PATH for CLI tools (vite, tsc, eslint, prettier, etc.)
  home.sessionPath = [ "$HOME/.node_modules/node_modules/.bin" ];

  # Activation: merge deps from cloud-data + front-data, generate package.json, npm install
  home.activation.sharedNodeModules = lib.hm.dag.entryAfter ["linkGeneration"] ''
    NODE_MODULES="$HOME/.node_modules"
    PKG_JSON="$NODE_MODULES/package.json"
    LOCK="$NODE_MODULES/node_modules/.package-lock.json"

    CLOUD_DEPS="$HOME/git/cloud/cloud-data/cloud-data-deps.json"
    FRONT_DEPS="$HOME/git/front/front-data/front-deps.json"
    FALLBACK="$NODE_MODULES/package.json.fallback"

    # Ensure package.json is writable (may be read-only from previous generation)
    [ -f "$PKG_JSON" ] && chmod u+w "$PKG_JSON" 2>/dev/null || true

    # Generate package.json from deps JSONs (or use fallback)
    if [ -f "$CLOUD_DEPS" ] || [ -f "$FRONT_DEPS" ]; then
      printf "[node-deps.nix] Merging deps from cloud-data + front-data...\n"
      PATH="${nodejs}/bin:$PATH" ${nodejs}/bin/node -e "
        const fs = require('fs');
        const deps = {}, devDeps = {};
        const take = (obj, target) => {
          for (const [k, v] of Object.entries(obj || {})) {
            if (!target[k] || v > target[k]) target[k] = v;
          }
        };
        for (const f of ['$CLOUD_DEPS', '$FRONT_DEPS']) {
          if (!fs.existsSync(f)) continue;
          try {
            const d = JSON.parse(fs.readFileSync(f, 'utf8'));
            take(d.node?.merged?.dependencies, deps);
            take(d.node?.merged?.devDependencies, devDeps);
          } catch (e) { console.error('WARN: ' + f + ': ' + e.message); }
        }
        // Ensure essential tools are always present
        if (!deps['tsx'] && !devDeps['tsx']) devDeps['tsx'] = '^4.19.0';
        if (!deps['typescript'] && !devDeps['typescript']) devDeps['typescript'] = '^5.7.0';
        const sort = o => Object.fromEntries(Object.entries(o).sort(([a],[b]) => a.localeCompare(b)));
        const pkg = {
          name: 'shared-node-modules',
          private: true,
          description: 'Auto-generated by node-deps.nix from cloud-deps.json + front-deps.json',
          dependencies: sort(deps),
          devDependencies: sort(devDeps)
        };
        fs.writeFileSync('$PKG_JSON', JSON.stringify(pkg, null, 2) + '\n');
        const total = Object.keys(deps).length + Object.keys(devDeps).length;
        console.log('package.json: ' + total + ' packages merged');
      " || {
        printf "[node-deps.nix] WARN: merge failed, using fallback\n"
        cp "$FALLBACK" "$PKG_JSON" 2>/dev/null || true
      }
    else
      printf "[node-deps.nix] No deps JSONs found, using fallback\n"
      cp "$FALLBACK" "$PKG_JSON" 2>/dev/null || true
    fi

    # npm install if package.json is newer than lock
    if [ -f "$PKG_JSON" ]; then
      if [ ! -d "$NODE_MODULES/node_modules" ] || [ "$PKG_JSON" -nt "$LOCK" ]; then
        printf "[node-deps.nix] npm install: ~/.node_modules/\n"
        PATH="${nodejs}/bin:$PATH" $DRY_RUN_CMD ${nodejs}/bin/npm install \
          --prefix "$NODE_MODULES" \
          --no-audit --no-fund --legacy-peer-deps || true
      else
        printf "[node-deps.nix] ~/.node_modules/ is up to date\n"
      fi
    fi
  '';

  # Symlink node_modules into stdio MCP src/ dirs so ESM imports resolve.
  # NODE_PATH only works for CJS require() — ESM import ignores it and walks
  # the filesystem up from the importing file looking for node_modules/.
  home.activation.mcpNodeModulesSymlinks = lib.hm.dag.entryAfter ["sharedNodeModules"] ''
    SHARED="$HOME/.node_modules/node_modules"
    MCP_DIRS="
      $HOME/git/cloud/a_solutions/bc-obs_c3-specs-docs-mcp/src
      $HOME/git/cloud/a_solutions/ca-dat_c3-diego-personal-data-mcp/src
    "
    for dir in $MCP_DIRS; do
      [ -d "$dir" ] || continue
      target="$dir/node_modules"
      if [ -L "$target" ]; then
        continue  # already a symlink
      elif [ -d "$target" ]; then
        continue  # real node_modules, don't override
      fi
      ln -s "$SHARED" "$target"
      printf "[node-deps.nix] Symlinked %s -> shared node_modules\n" "$target"
    done
  '';
}
