# System Protection — Desktop Session (KDE Plasma 6 memory caps + watchdog)
#
# Why: long-uptime KDE sessions bloat kwin_wayland and plasmashell until they
# crash the Wayland session (live evidence: 2026-04-28 21:15, 2-day session,
# kwin 1.1G+815M swap, plasmashell 692M+983M swap, ksystemstats 42min CPU
# leak). earlyoom won't intervene — it has --avoid for these services and
# rightly so (killing kwin tears the session).
#
# This module declaratively:
#   1. Drops systemd USER drop-ins setting MemoryHigh/MemoryMax per leaky service
#   2. Installs a periodic user-timer watchdog that proactively restarts/notifies
#      BEFORE the hard ceiling kicks in (so user sees no glitch)
#
# Source of truth: ./system-protection-desktop-session.json
# Engine:          ./system-protection-desktop-session-watchdog.sh
# Tester:          ./test-system-protection-desktop-session.sh
#
# Imported by: system-protection.nix (orchestrator)
#
{ config, pkgs, lib, ... }:

let
  cfg = builtins.fromJSON (builtins.readFile ./system-protection-desktop-session.json);

  mkDropIn = svcName: svcCfg: ''
    # Generated by system-protection-desktop-session.nix
    # Source of truth: system-protection-desktop-session.json
    # Service: ${svcName}
    [Service]
    MemoryHigh=${svcCfg.MemoryHigh}
    MemoryMax=${svcCfg.MemoryMax}
  '';

  # Map each service in JSON → ".config/systemd/user/<svc>.d/memory-cap.conf"
  dropInFiles = lib.mapAttrs' (svcName: svcCfg:
    lib.nameValuePair
      ".config/systemd/user/${svcName}.d/memory-cap.conf"
      { text = mkDropIn svcName svcCfg; }
  ) cfg.services;

  watchdogIntervalMin = cfg.watchdog.interval_minutes;
  watchdogBootDelay   = cfg.watchdog.boot_delay_minutes;
in
{
  home.packages = [ pkgs.jq pkgs.libnotify ];

  home.file = dropInFiles // {
    # Stable config path — the watchdog reads this
    ".config/system-protection-desktop-session/services.json".source =
      ./system-protection-desktop-session.json;

    # Watchdog engine on $PATH
    ".local/bin/system-protection-desktop-watchdog" = {
      source = ./system-protection-desktop-session-watchdog.sh;
      executable = true;
    };
  };

  systemd.user.services.system-protection-desktop-watchdog = {
    Unit = {
      Description = "Plasma memory watchdog (proactive restart of leaky services)";
    };
    Service = {
      Type = "oneshot";
      ExecStart = "%h/.local/bin/system-protection-desktop-watchdog";
    };
  };

  systemd.user.timers.system-protection-desktop-watchdog = {
    Unit.Description = "Periodic Plasma memory check";
    Timer = {
      OnBootSec = "${toString watchdogBootDelay}min";
      OnUnitActiveSec = "${toString watchdogIntervalMin}min";
    };
    Install.WantedBy = [ "timers.target" ];
  };
}
