# Fish shell configuration — FULLY DATA-DRIVEN (same contract as bb_flakes_termux).
#
# Every abbreviation, alias and function comes from ONE file:
#   modules/data/fish-commands.json
# and so does the "Aliases & Functions" section of fish_greeting (via the generated
# __cloud_commands_help). Adding a command means editing that JSON — never this file
# — so the greeting can no longer advertise something that isn't installed. Both
# machines previously hand-wrote that section inside fish_greeting.fish and both
# drifted from reality independently.
#
# The command SET is per-machine on purpose (plasma/qdbus/chromium here, proot/termux
# there); the schema and the generator shape are shared, so the rendered section reads
# identically on both.
{ config, pkgs, lib, inputs, ... }:

let
  cmds = builtins.fromJSON (builtins.readFile ../../data/fish-commands.json);

  # ── generators ─────────────────────────────────────────────────────
  toAttrs = f: list: builtins.listToAttrs (map f list);

  abbrAttrs  = toAttrs (a: { name = a.name; value = a.cmd; }) cmds.abbrs;
  aliasAttrs = toAttrs (a: { name = a.name; value = a.cmd; }) cmds.aliases;
  fnAttrs    = toAttrs (f: {
    name  = f.name;
    value = builtins.readFile (./fish/functions + "/${f.file}");
  }) cmds.functions;

  # ── greeting help — generated from the SAME data ────────────────────
  # Rendered at build time into a fish function body: zero subprocesses at
  # greeting time.
  visible = list: builtins.filter (x: !(x.hidden or false)) list;

  # `·` in the ·abbr suffix is 2 bytes but ONE column, and stringLength counts
  # bytes — measuring it raw left every abbr row a column left of its neighbours.
  dispLen = x: builtins.stringLength (builtins.replaceStrings [ "·" ] [ "x" ] x);
  pad = s:
    let n = 19 - dispLen s;
    in s + lib.concatStrings (lib.genList (_: " ") (if n > 1 then n else 1));

  # Descriptions land inside a double-quoted fish string, so $, " and \ must be
  # escaped — an unescaped $HOME in a desc would be EXPANDED at greeting time.
  esc = builtins.replaceStrings [ "\\" "\"" "$" ] [ "\\\\" "\\\"" "\\$" ];

  line = color: suffix: item:
    ''set_color ${color}; echo -n "    ${pad (item.name + suffix)}"; set_color normal; echo "${esc (item.desc or "")}"'';

  itemsFor = gid:
       map (line "cyan"   " ·abbr") (builtins.filter (a: (a.group or "other") == gid) (visible cmds.abbrs))
    ++ map (line "yellow" "")       (builtins.filter (a: (a.group or "other") == gid) (visible cmds.aliases))
    ++ map (line "green"  "()")     (builtins.filter (f: (f.group or "other") == gid) (visible cmds.functions));

  groupBlock = g:
    let items = itemsFor g.id;
    in if items == [] then "" else ''
      set_color cyan; echo "  ${g.title}:"
      set_color normal
      ${lib.concatStringsSep "\n      " items}
    '';

  helpBody = ''
    # GENERATED from modules/data/fish-commands.json by fish.nix — do not edit.
    # Legend: name ·abbr = expands on space · name() = function · bare name = alias.
    set_color --bold yellow
    echo "── Aliases & Functions ────────────────────────────────────────────────────────────────────────"
    set_color normal
    ${lib.concatStringsSep "\n    " (map groupBlock cmds.groups)}
    set_color --dim; echo "    (source: modules/data/fish-commands.json — hhelp alias for the full dump)"; set_color normal
  '';

  # ── env vars ────────────────────────────────────────────────────────
  # ONE copy, read out of the fetched unix-repo (same convention as qute.nix and
  # konsole-ssh-manager). The file lists NAMES only — values are read live at
  # greeting time — so it is genuinely machine-independent and must not be
  # duplicated here; bb_flakes_termux is a `path:` flake and cannot reach outside
  # its own src/, which is why the file physically lives on that side.
  envs = builtins.fromJSON (builtins.readFile
    "${inputs.unix-repo}/bb_flakes_termux/src/modules/data/fish-envvars.json");

  padE = s:
    let n = 32 - builtins.stringLength s;
    in s + lib.concatStrings (lib.genList (_: " ") (if n > 1 then n else 1));

  envLine = v: ''
    set_color yellow; echo -n "    ${padE v.name}"
        if set -q ${v.name}
          ${if (v.secret or false)
            then ''set_color --dim green; echo "set (hidden)"''
            else ''set_color normal; echo (string sub -l 72 -- "''$${v.name}")''}
        else
          set_color --dim red; echo "unset"
        end
        set_color normal'';

  envGroupBlock = g:
    let items = map envLine (builtins.filter (v: (v.group or "other") == g.id) envs.vars);
    in if items == [] then "" else ''
      set_color cyan; echo "  ${g.title}:"
      set_color normal
      ${lib.concatStringsSep "\n      " items}
    '';

  envHelpBody = ''
    # GENERATED by fish.nix from bb_flakes_termux/src/modules/data/fish-envvars.json.
    # Names from that file; values read live, so `unset` is real.
    set_color --bold yellow
    echo "── Env Vars ───────────────────────────────────────────────────────────────────────────────────"
    set_color normal
    ${lib.concatStringsSep "\n    " (map envGroupBlock envs.groups)}
    set_color --dim; echo "    (source: fish-envvars.json — secrets shown as 'set (hidden)')"; set_color normal
  '';
in
{
  programs.fish = {
    enable = true;

    shellAbbrs   = abbrAttrs;
    shellAliases = aliasAttrs;

    functions = fnAttrs // {
      __cloud_commands_help = helpBody;
      __cloud_envvars_help  = envHelpBody;
    };

    interactiveShellInit = builtins.readFile ./fish/interactiveShellInit.fish;
  };
}
