#!/usr/bin/env bash
# waydroid-sensors — host-side Android sensors HAL for Waydroid (IIO-backed).
#
# Data-driven from build.json. The C++ daemon (src/code) is the upstream Waydroid
# gbinder/HIDL @1.0 ISensors layer with an IIO data source swapped in. Nothing the
# engine cares about is hardcoded: IIO device name, poll rate, mount matrix and the
# binder node all come from build.json and are rendered into a runtime conf.
#
#   ./build.sh build      # nix build the daemon -> dist/ ; render dist conf
#   ./build.sh conf       # (re)render dist/waydroid-sensors.conf from build.json
#   ./build.sh calibrate  # live-print IIO accel (m/s^2) per axis while you rotate the SP8
#   ./build.sh run        # run the daemon in the foreground (for testing)
#   ./build.sh takeover   # stop the in-container stub HAL + restart sensorservice
#   ./build.sh install    # install binary path + render & install the user systemd unit + conf
#   ./build.sh enable     # systemctl --user enable --now + takeover
#   ./build.sh status     # daemon + live Android sensor count
#   ./build.sh test       # run src/test/test.sh
#   ./build.sh clean      # rm dist/
#   ./build.sh ship       # build + install + enable
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$ROOT/build.json"
SRC="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.src)")"
CODE="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.code)")"
DIST="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.dist)")"
BINARY_NAME="$(node -e "process.stdout.write(require('$CONFIG').paths.binary)")"
CONF="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.conf)")"
GBINDER_CONF="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.gbinder_conf)")"
UNIT_TPL="$ROOT/$(node -e "process.stdout.write(require('$CONFIG').paths.systemd_unit_tpl)")"

c_g='\033[0;32m'; c_y='\033[0;33m'; c_r='\033[0;31m'; c_0='\033[0m'
log()  { printf "${c_g}[waydroid-sensors]${c_0} %s\n" "$*"; }
warn() { printf "${c_y}[waydroid-sensors]${c_0} %s\n" "$*"; }
die()  { printf "${c_r}[waydroid-sensors] ERROR:${c_0} %s\n" "$*" >&2; exit 1; }
get()  { node -e "const c=require('$CONFIG');const v='$1'.split('.').reduce((o,k)=>o&&o[k],c);process.stdout.write(String(v??''))"; }

# ── waydroid container shell (root + `--` so flags reach android), like da_waydroid-apps
WDSH=( waydroid )
detect_priv() { if waydroid shell -- true >/dev/null 2>&1; then WDSH=( waydroid ); else WDSH=( sudo waydroid ); fi; }
wd_shell() { "${WDSH[@]}" shell -- "$@"; }
session_running() { waydroid status 2>/dev/null | grep -q 'Session:.*RUNNING'; }

expand_tilde() { case "$1" in "~/"*) printf '%s' "$HOME/${1#\~/}";; *) printf '%s' "$1";; esac; }

# ── conf: render the runtime KEY=VALUE file from build.json (data-driven) ───
cmd_conf() {
  mkdir -p "$(dirname "$CONF")"
  node -e "
    const c=require('$CONFIG'); const i=c.iio, m=i.mount;
    const L=[
      '# generated by build.sh conf — edit build.json, not this file',
      'IIO_NAME='+i.name,
      'POLL_INTERVAL_MS='+i.poll_interval_ms,
      'AXIS_X_SRC='+m.x.src, 'AXIS_X_SIGN='+m.x.sign,
      'AXIS_Y_SRC='+m.y.src, 'AXIS_Y_SIGN='+m.y.sign,
      'AXIS_Z_SRC='+m.z.src, 'AXIS_Z_SIGN='+m.z.sign,
    ];
    require('fs').writeFileSync('$CONF', L.join('\n')+'\n');
  "
  # gbinder protocol map for our binder node (system gbinder.d omits anbox-hwbinder)
  node -e "
    const c=require('$CONFIG'); const d=c.binder.device, p=c.binder.protocol;
    const L=['# generated by build.sh conf','[Protocol]', d+' = '+p, '', '[ServiceManager]', d+' = '+p];
    require('fs').writeFileSync('$GBINDER_CONF', L.join('\n')+'\n');
  "
  log "rendered $CONF + $GBINDER_CONF"
}

# ── build: nix build daemon -> dist/ ────────────────────────────────────────
cmd_build() {
  mkdir -p "$DIST"
  log "nix build (reproducible flake)…"
  local out
  out="$(nix build "path:$SRC#waydroid-sensord" --no-link --print-out-paths)"
  command cp -f "$out/bin/$BINARY_NAME" "$DIST/$BINARY_NAME"
  chmod +w "$DIST/$BINARY_NAME"
  log "built $DIST/$BINARY_NAME"
  cmd_conf
}

# ── calibrate: live IIO accel readout to resolve the mount matrix ───────────
cmd_calibrate() {
  local name secs; name="$(get iio.name)"; secs="${1:-20}"
  local dev=""
  for d in /sys/bus/iio/devices/iio:device*; do
    [ -r "$d/name" ] || continue
    [ "$(cat "$d/name" 2>/dev/null)" = "$name" ] || continue
    [ -r "$d/in_accel_x_raw" ] && { dev="$d"; break; }
  done
  [ -n "$dev" ] || die "no IIO device named '$name' with in_accel_*_raw"
  local scale; scale="$(cat "$dev/in_accel_scale" 2>/dev/null || echo 1)"
  log "device $dev  scale=$scale  (raw*scale = m/s^2)"
  log "Rotate the Surface slowly. The axis reading ~ +/-9.8 is the one pointing down/up."
  log "Goal mapping (Android): flat face-up -> Z=+9.8 ; upright portrait -> Y=+9.8 ; landscape -> X=+9.8"
  local end=$(( $(date +%s) + secs ))
  while [ "$(date +%s)" -lt "$end" ]; do
    local x y z
    x="$(cat "$dev/in_accel_x_raw")"; y="$(cat "$dev/in_accel_y_raw")"; z="$(cat "$dev/in_accel_z_raw")"
    node -e "const s=$scale;const f=v=>(v*s).toFixed(2).padStart(7);
      process.stdout.write('  raw x='+f($x)+'  y='+f($y)+'  z='+f($z)+'  (m/s^2)      \r')"
    sleep 0.3
  done
  echo
  log "Set build.json iio.mount so Android X/Y/Z match the goal, then: ./build.sh build"
}

# ── run: foreground daemon (testing) ────────────────────────────────────────
cmd_run() {
  [ -x "$DIST/$BINARY_NAME" ] || die "daemon not built — run: ./build.sh build"
  [ -f "$CONF" ] || cmd_conf
  session_running || warn "Waydroid session not RUNNING — binder node may be absent"
  local dev; dev="$(get binder.device)"
  [ -f "$GBINDER_CONF" ] || cmd_conf
  log "GBINDER_CONFIG_FILE=$GBINDER_CONF WAYDROID_SENSORS_CONF=$CONF $DIST/$BINARY_NAME $dev"
  GBINDER_CONFIG_FILE="$GBINDER_CONF" WAYDROID_SENSORS_CONF="$CONF" exec "$DIST/$BINARY_NAME" "$dev"
}

# ── wait_boot: block until the framework is fully up (boot-safety gate) ─────
# The HAL must NOT be present during SensorService init or it deadlocks the boot.
wait_boot() {
  detect_priv
  local prop to t=0; prop="$(get waydroid.boot_gate_prop)"; to="$(get waydroid.boot_gate_timeout_s)"
  log "boot-gate: waiting for $prop=1 (up to ${to}s) before starting the HAL…"
  while [ "$t" -lt "$to" ]; do
    [ "$(wd_shell getprop "$prop" 2>/dev/null | tr -d '\r')" = "1" ] && { log "boot-gate: framework up."; return 0; }
    sleep 3; t=$((t+3))
  done
  die "boot-gate: framework not up within ${to}s ($prop != 1) — refusing to start the HAL (would risk hanging boot)"
}

# ── stopstub: kill the in-container stub HAL so the HIDL name is free ───────
cmd_stopstub() {
  session_running || die "Waydroid session is not RUNNING"
  detect_priv
  local prop svc proc; prop="$(get waydroid.stub_prop)"; svc="$(get waydroid.stub_service)"; proc="$(get waydroid.stub_process)"
  log "stopping in-container stub ($svc / $proc)…"
  wd_shell sh -c "setprop $prop 0; setprop ctl.stop $svc; killall -9 $proc 2>/dev/null; true" || true
}

# ── takeover: re-run the full sequence so the framework binds OUR HAL ───────
# Order is critical: stop stub -> (re)register daemon -> restart framework.
cmd_takeover() {
  session_running || die "Waydroid session is not RUNNING"
  local unit; unit="$(get runtime.unit_name)"
  if systemctl cat "$unit" >/dev/null 2>&1; then
    log "restarting $unit (stops stub, re-registers, restarts framework via unit hooks)…"
    sudo systemctl restart "$unit" || die "systemctl restart $unit failed"
    sleep 5
  else
    warn "$unit not installed — doing a one-shot takeover (daemon must already be running)"
    cmd_stopstub
    detect_priv
    wd_shell sh -c "$(get waydroid.framework_restart)" || true
    sleep 5
  fi
  cmd_status
}

# ── install: render the rendered systemd unit into dist/ for reference ──────
# On NixOS /etc is read-only, so the PERMANENT home is the NixOS module
# (src/nix/waydroid-sensors.nix) imported into the host flake + `build.sh switch`.
# `enable` below runs it immediately as a transient root service for validation.
cmd_install() {
  [ -x "$DIST/$BINARY_NAME" ] || die "build first: ./build.sh build"
  local dev wbin; dev="$(get binder.device)"; wbin="$(command -v waydroid)"
  [ -n "$wbin" ] || die "waydroid not found in PATH"
  local rendered="$DIST/$(get runtime.unit_name)"
  node -e "
    const fs=require('fs');let t=fs.readFileSync('$UNIT_TPL','utf8');
    const r={'@BINARY@':'$DIST/$BINARY_NAME','@CONF@':'$CONF','@DEVICE@':'$dev','@WAYDROID@':'$wbin',
             '@STUBPROP@':'$(get waydroid.stub_prop)','@STUBSVC@':'$(get waydroid.stub_service)',
             '@STUBPROC@':'$(get waydroid.stub_process)','@FWRESTART@':'$(get waydroid.framework_restart)',
             '@BOOTGATE@':'$(get waydroid.boot_gate_prop)','@BOOTTIMEOUT@':'$(get waydroid.boot_gate_timeout_s)'};
    for(const k in r) t=t.split(k).join(r[k]);
    fs.writeFileSync('$rendered',t);
  "
  log "rendered reference unit -> $rendered"
  log "permanent install = import src/nix/waydroid-sensors.nix into the host flake + build.sh switch"
  log "to validate/run now:  ./build.sh enable"
}

# ── bootprops: override Waydroid framework props applied at container start ──
# Roots the real fix: the framework reads waydroid.stub_sensors_hal at boot, so we
# must set it to 0 in waydroid_base.prop BEFORE the container starts.
cmd_bootprops() {
  local f; f="$(expand_tilde "$(get waydroid.base_prop_path)")"
  mkdir -p "$(dirname "$f")"; [ -f "$f" ] || : > "$f"
  node -e "
    const fs=require('fs'); const f='$f';
    const props=require('$CONFIG').waydroid.boot_props||{};
    let lines=fs.readFileSync(f,'utf8').split('\n');
    for(const [k,v] of Object.entries(props)){
      lines=lines.filter(l=>l.trim()!==''&&l.split('=')[0].trim()!==k);
      lines.push(k+'='+v);
    }
    fs.writeFileSync(f, lines.filter(l=>l.trim()!=='').join('\n')+'\n');
  "
  log "boot props set in $f:"; node -e "Object.entries(require('$CONFIG').waydroid.boot_props).forEach(([k,v])=>console.log('    '+k+'='+v))"
  warn "boot props apply on the NEXT container start — restart the session to take effect."
}

# ── enable: run the HAL as a transient root system service + take over ──────
# NixOS-correct runtime (no /etc writes). Order: stop stub -> register -> restart framework.
cmd_enable() {
  session_running || die "Waydroid session is not RUNNING"
  [ -x "$DIST/$BINARY_NAME" ] || die "build first: ./build.sh build"
  [ -f "$CONF" ] || cmd_conf
  local unit dev; dev="$(get binder.device)"
  unit="$(get runtime.unit_name)"; unit="${unit%.service}"
  wait_boot              # boot-safety: never register the HAL during SensorService init
  cmd_bootprops          # ensure framework boots with stub disabled (applies next container start)
  cmd_stopstub
  log "starting transient root service '$unit' (systemd-run)…"
  sudo systemctl reset-failed "$unit.service" 2>/dev/null || true
  sudo systemctl stop "$unit.service" 2>/dev/null || true
  sudo systemd-run --unit="$unit" --collect \
       --setenv=GBINDER_CONFIG_FILE="$GBINDER_CONF" \
       --setenv=WAYDROID_SENSORS_CONF="$CONF" \
       "$DIST/$BINARY_NAME" "$dev" || die "systemd-run failed"
  sleep 2
  detect_priv
  log "restarting Android framework so sensorservice binds our HAL…"
  wd_shell sh -c "$(get waydroid.framework_restart)" || true
  sleep 6
  cmd_status
}

cmd_status() {
  local unit; unit="$(get runtime.unit_name)"
  printf "service: "; systemctl is-active "$unit" 2>/dev/null || echo "inactive/not-installed"
  pgrep -af "$BINARY_NAME" 2>/dev/null | sed 's/^/  proc: /' || true
  if session_running; then
    detect_priv
    echo "--- Android sensorservice (first lines) ---"
    wd_shell dumpsys sensorservice 2>/dev/null | sed -n '1,8p' | tr -d '\r' | sed 's/^/  /'
  else
    warn "Waydroid session not running"
  fi
}

cmd_test()  { bash "$ROOT/src/test/test.sh"; }
cmd_clean() { rm -rf "$DIST"; log "cleaned dist/"; }
cmd_ship()  { cmd_build; cmd_install; cmd_enable; }

case "${1:-build}" in
  build) cmd_build ;;
  conf) cmd_conf ;;
  calibrate) shift; cmd_calibrate "${1:-20}" ;;
  run) cmd_run ;;
  stopstub) cmd_stopstub ;;
  bootprops) cmd_bootprops ;;
  takeover) cmd_takeover ;;
  install) cmd_install ;;
  enable) cmd_enable ;;
  status) cmd_status ;;
  test) cmd_test ;;
  clean) cmd_clean ;;
  ship) cmd_ship ;;
  *) die "unknown command '$1' (build|conf|calibrate|run|takeover|install|enable|status|test|clean|ship)" ;;
esac
