#!/usr/bin/env bash
# test-bootloader-yield.sh — verify NixOS has fully yielded bootloader
# management to the aa_bootloader/ engine and there are no stale GRUB,
# Kubuntu or old-Arch-UUID references.
#
# Run after `build.sh switch`. Returns 0 if all checks pass.
# Per FIRE RULE 5: every cleanup claim must have a tester.

set -u
PASS=0; FAIL=0
declare -a FAILED_TESTS=()

ok()    { echo "[OK]   $1"; PASS=$((PASS+1)); }
fail()  { echo "[FAIL] $1"; FAIL=$((FAIL+1)); FAILED_TESTS+=("$1"); }

REPO="$(cd "$(dirname "$0")/../../.." && pwd)"

# T1 — NixOS GRUB module disabled (yield)
if grep -q "boot.loader.grub.enable = lib.mkForce false" "$REPO/aa_desk-usr_x86_surface-linux_nixos/src/modules/nixos_yield.nix" 2>/dev/null; then
  ok "T1 nixos_yield.nix disables boot.loader.grub.enable"
else
  fail "T1 nixos_yield.nix not yielding GRUB"
fi

# T2 — UEFI default boot is rEFInd (Boot0007)
EFIBOOTMGR=$(command -v efibootmgr 2>/dev/null || ls /nix/store/*-efibootmgr-*/bin/efibootmgr 2>/dev/null | head -1)
if [ -x "$EFIBOOTMGR" ]; then
  if sudo "$EFIBOOTMGR" 2>/dev/null | grep -E "^BootOrder:" | head -1 | grep -q "^BootOrder: 0007"; then
    ok "T2 UEFI BootOrder default is rEFInd (0007)"
  else
    fail "T2 UEFI BootOrder default is not rEFInd"
  fi
else
  fail "T2 efibootmgr not found"
fi

# T3 — refind.conf was generated by aa_bootloader engine (header marker)
if sudo grep -q "AUTO-GENERATED by aa_bootloader" /boot/efi/EFI/refind/refind.conf 2>/dev/null; then
  ok "T3 refind.conf was rendered by aa_bootloader/src/gen/render-refind-conf.sh"
else
  fail "T3 refind.conf header marker missing — engine output overwritten?"
fi

# T4 — src/dist boot.json agree on the rescue-os-debian entry
if [ -f "$REPO/aa_bootloader/src/boot.json" ] && [ -f "$REPO/aa_bootloader/dist/adapters/nixos/boot.json" ]; then
  if diff <(jq '.grub.menu.debian' "$REPO/aa_bootloader/src/boot.json") \
          <(jq '.grub.menu.debian' "$REPO/aa_bootloader/dist/adapters/nixos/boot.json") >/dev/null 2>&1; then
    ok "T4 src/dist boot.json debian entry in sync"
  else
    fail "T4 dist/ adapter out of date — run aa_bootloader/build.sh generate"
  fi
fi

# T5 — no orphan ACTIVE GRUB references in host flake source
# (skip comment-only lines starting with '#', and skip the tester itself,
#  nixos_yield.nix, and cloud-data-power.json which all legitimately mention GRUB)
STALE=$(grep -rEn "^[^#]*(boot\.loader\.grub\.enable\s*=\s*true|grub-extra-entries|hardware_grub|update-grub\.sh|/boot/grub/grub\.cfg)" \
  "$REPO/aa_desk-usr_x86_surface-linux_nixos/src/" --include='*.nix' --include='*.json' --include='*.sh' 2>/dev/null \
  | grep -vE "nixos_yield\.nix|cloud-data-power\.json|test-bootloader-yield\.sh" | wc -l)
if [ "$STALE" -eq 0 ]; then
  ok "T5 no stale GRUB references in host flake source"
else
  fail "T5 host flake has $STALE non-comment lines with stale GRUB refs"
fi

# T6 — /mnt/shared-lib mount declared, /mnt/kubuntu NOT in source
if grep -q '"/mnt/shared-lib"' "$REPO/aa_desk-usr_x86_surface-linux_nixos/src/modules/hardware_filesystems.nix" 2>/dev/null; then
  ok "T6a /mnt/shared-lib declared in fileSystems"
else
  fail "T6a /mnt/shared-lib missing from fileSystems"
fi
if grep -q '"/mnt/kubuntu"' "$REPO/aa_desk-usr_x86_surface-linux_nixos/src/modules/hardware_filesystems.nix" 2>/dev/null; then
  fail "T6b /mnt/kubuntu still in fileSystems"
else
  ok "T6b /mnt/kubuntu removed from fileSystems"
fi

# T7 — rescue-os-debian UUID is the canonical one in aa_bootloader and main.tf
SRC_UUID=$(jq -r '.grub.menu.debian.root_uuid' "$REPO/aa_bootloader/src/boot.json" 2>/dev/null)
if [ "$SRC_UUID" = "42ccd674-d035-497d-b0eb-bffa28c5144c" ]; then
  ok "T7a aa_bootloader/src/boot.json uses rescue-os-debian UUID"
else
  fail "T7a aa_bootloader/src/boot.json has unexpected root_uuid: $SRC_UUID"
fi
if grep -q "1648a2fb" "$REPO/main.tf" 2>/dev/null; then
  fail "T7b main.tf still references old Arch UUID 1648a2fb"
else
  ok "T7b main.tf has no old Arch UUID references"
fi

# T8 — /mnt/kubuntu purged from fallback-OS install scripts
COUNT=$(grep -rn "/mnt/kubuntu" "$REPO/ab_fallback_os/" \
  --include='*.sh' --include='*.json' --include='*.md' \
  --exclude-dir=loot --exclude-dir=container 2>/dev/null | wc -l)
if [ "$COUNT" -eq 0 ]; then
  ok "T8 fallback-OS install scripts no longer reference /mnt/kubuntu"
else
  fail "T8 $COUNT remaining /mnt/kubuntu refs in fallback-OS install scripts"
fi

# T9 — host-flake boot.json is byte-equal to dist/adapters/nixos/boot.json
# (it's a generated artifact deployed by aa_bootloader/build.sh deploy --target nixos
#  — hardware_bootloader_boot.nix reads it as ./boot.json)
SRC="$REPO/aa_bootloader/dist/adapters/nixos/boot.json"
DST="$REPO/aa_desk-usr_x86_surface-linux_nixos/src/modules/boot.json"
if [ -f "$SRC" ] && [ -f "$DST" ] && cmp -s "$SRC" "$DST"; then
  ok "T9 host flake boot.json matches aa_bootloader/dist/ (deployed in sync)"
else
  fail "T9 host flake boot.json out of sync — run 'aa_bootloader/build.sh deploy --target nixos'"
fi

# T10 — ab_arch-surface_fallback_desk archived
if [ -d "$REPO/ab_fallback_os/ab_arch-surface_fallback_desk" ]; then
  fail "T10 ab_arch-surface_fallback_desk still in active fallback dir"
else
  ok "T10 ab_arch-surface_fallback_desk moved out of active fallback dir"
fi

echo ""
echo "──────────────────────────────────────────"
echo "Bootloader-yield test summary: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "Failed tests:"
  for t in "${FAILED_TESTS[@]}"; do echo "  - $t"; done
  exit 1
fi
exit 0
