#!/bin/sh
# render-grub-cfg-preview.sh — human-readable preview of the GRUB menu structure
# encoded in boot.json. NOT a deployable grub.cfg.
#
# Phase 1: NixOS still authors /boot/grub/grub.cfg via boot.loader.grub.extraEntries.
# This script's output is for `build.sh plan` (diff against live grub.cfg) and
# for human review.
#
# Phase 3: gen/render-grub-cfg.sh (TBD) will render a deployable grub.cfg.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")"

# shellcheck source=lib/log.sh
. "$ROOT_DIR/src/engine/lib/log.sh"

BOOT_JSON="$ROOT_DIR/src/boot.json"
DIST_PREVIEWS="$ROOT_DIR/dist/previews"
OUT="$DIST_PREVIEWS/grub-menu.txt"

# shellcheck source=lib/json.sh
. "$ROOT_DIR/src/engine/lib/json.sh"

mkdir -p "$DIST_PREVIEWS"

log "Rendering GRUB menu preview → $OUT"

{
    echo "# GRUB MENU STRUCTURE (preview from boot.json)"
    echo "# GENERATED $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""

    echo "── UI ─────────────────────────────────────────────"
    echo "timeout:           $(jq_get '.grub.ui.timeout')"
    echo "default:           $(jq_get '.grub.ui.default')"
    echo "gfxmode:           $(jq_get '.grub.ui.gfxmode')"
    echo "background_color:  $(jq_get '.grub.ui.background_color')"
    echo ""

    echo "── ENTRIES ────────────────────────────────────────"
    for os in arch kali windows; do
        enabled=$(jq -r ".grub.menu.${os}.enabled // false" "$BOOT_JSON")
        if [ "$enabled" = "true" ]; then
            label=$(jq -r ".grub.menu.${os}.label" "$BOOT_JSON")
            echo "[$os] $label"
        fi
    done

    if [ "$(jq -r '.grub.menu.usb.enabled // false' "$BOOT_JSON")" = "true" ]; then
        jq -r '.grub.menu.usb.entries[] | "[usb] \(.label)"' "$BOOT_JSON"
    fi

    if [ "$(jq -r '.grub.menu.firmware.enabled // false' "$BOOT_JSON")" = "true" ]; then
        echo "[firmware] $(jq_get '.grub.menu.firmware.label')"
    fi

    echo ""
    echo "── NIXOS (auto-generated by NixOS in Phase 1) ─────"
    echo "  see /boot/grub/grub.cfg for the actual NixOS entries"
    echo "  rollback_entries.auto_walk_profiles: $(jq_get '.grub.menu.nixos.rollback_entries.auto_walk_profiles')"
    echo "  rollback_entries.max:                $(jq_get '.grub.menu.nixos.rollback_entries.max')"
    echo "  specialisations:                     $(jq -r '.grub.menu.nixos.specialisations | join(", ")' "$BOOT_JSON")"
    echo ""

    echo "── KERNEL CMDLINE (hibernate slice managed here) ──"
    echo "default: $(jq -r '.swap_hibernate.kernel_params | join(" ")' "$BOOT_JSON")"
    echo "rescue:  strip=$(jq -r '.kernel.specialisations.rescue.params_strip | join(",")' "$BOOT_JSON")  add=$(jq -r '.kernel.specialisations.rescue.params_add | join(",")' "$BOOT_JSON")"

} > "$OUT"

log "Wrote: $OUT"
