# Front-end npm dependencies — merged from front-deps.json at activation time.
# Generated by front build system, synced to front-data/ by Dagu.
args@{ config, lib, pkgs, ... }:

let
  # Take nodejs from module args (flake.nix _module.args = pkgsUnstable
  # nodejs_22, i.e. >=22.12) — hardcoding pkgs.nodejs_22 here pinned every
  # npm install to 24.05's node 22.10, which vite 8 / unplugin 3 reject
  # (the EBADENGINE spam) and which native addons compiled against.
  nodejs = args.nodejs or pkgs.nodejs_22;
in {
  options.nodeNpmDeps.front = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = {};
    description = "Front-end npm dependencies (auto-merged from front-deps.json)";
  };

  # Activation: read front-deps.json → write merged output
  config.home.activation.mergeFrontDeps = lib.hm.dag.entryBefore ["sharedNodeModules"] ''
    FRONT_DEPS="$HOME/git/front/front-data/front-deps.json"
    FRONT_OUT="$HOME/.node_modules/.front-deps-merged.json"

    if [ -f "$FRONT_DEPS" ]; then
      PATH="${nodejs}/bin:$PATH" ${nodejs}/bin/node -e "
        const fs = require('fs');
        const deps = {};
        try {
          const d = JSON.parse(fs.readFileSync('$FRONT_DEPS', 'utf8'));
          const take = (obj) => {
            for (const [k, v] of Object.entries(obj || {})) {
              if (!deps[k] || v > deps[k]) deps[k] = v;
            }
          };
          take(d.node?.merged?.dependencies);
          take(d.node?.merged?.devDependencies);
        } catch (e) { console.error('WARN: front-deps: ' + e.message); }
        fs.writeFileSync('$FRONT_OUT', JSON.stringify(deps, null, 2) + '\n');
        console.log('[node-npm-deps-front] ' + Object.keys(deps).length + ' front deps extracted');
      " || printf "[node-npm-deps-front] WARN: merge failed\n"
    else
      printf "[node-npm-deps-front] No front-deps.json found\n"
      echo '{}' > "$FRONT_OUT" 2>/dev/null || true
    fi
  '';
}
