# Shared ~/.node_modules — single npm install for all repos.
#
# Architecture:
#   node-npm-deps.nix          ← this file (orchestrator: merge + install)
#   ├── node-npm-deps-list.nix  ← static known deps (tsx, MCP SDK, fastify, etc.)
#   ├── node-npm-deps-cloud.nix ← auto-merged from build-flakes_termux.json (.deps)
#   └── node-npm-deps-front.nix ← auto-merged from front-data/front-deps.json
#
# Resolution: static list always wins → cloud deps → front deps → npm install
# Skips install if package.json unchanged since last run.
args@{ config, lib, pkgs, ... }:

let
  # Take nodejs from module args (flake.nix _module.args = pkgsUnstable
  # nodejs_22, i.e. >=22.12) — hardcoding pkgs.nodejs_22 here pinned every
  # npm install to 24.05's node 22.10, which vite 8 / unplugin 3 reject
  # (the EBADENGINE spam) and which native addons compiled against.
  nodejs = args.nodejs or pkgs.nodejs_22;
in {
  imports = [
    ./node-npm-deps-list.nix
    ./node-npm-deps-cloud.nix
    ./node-npm-deps-front.nix
  ];

  # Set NODE_PATH so all tools resolve from shared dir
  home.sessionVariables.NODE_PATH = "$HOME/.node_modules/node_modules";

  # Add .bin to PATH for CLI tools (tsx, tsc, vite, eslint, prettier, etc.)
  home.sessionPath = [ "$HOME/.node_modules/node_modules/.bin" ];

  # Activation: merge all 3 sources → generate package.json → npm install
  home.activation.sharedNodeModules = lib.hm.dag.entryAfter ["linkGeneration" "mergeCloudDeps" "mergeFrontDeps"] ''
    NODE_MODULES="$HOME/.node_modules"
    PKG_JSON="$NODE_MODULES/package.json"
    LOCK="$NODE_MODULES/node_modules/.package-lock.json"
    mkdir -p "$NODE_MODULES"

    CLOUD_MERGED="$NODE_MODULES/.cloud-deps-merged.json"
    FRONT_MERGED="$NODE_MODULES/.front-deps-merged.json"

    # Ensure package.json is writable
    [ -f "$PKG_JSON" ] && chmod u+w "$PKG_JSON" 2>/dev/null || true

    # Static deps from node-npm-deps-list.nix (Nix option → JSON)
    STATIC_DEPS='${builtins.toJSON config.nodeNpmDeps.static}'

    PATH="${nodejs}/bin:$PATH" ${nodejs}/bin/node -e "
      const fs = require('fs');
      const deps = {};

      // 1. Load static deps (always present, highest priority)
      const staticDeps = JSON.parse('$STATIC_DEPS');
      Object.assign(deps, staticDeps);

      // 2. Merge cloud deps (lower priority — won't override static)
      const mergeFile = (path) => {
        if (!fs.existsSync(path)) return;
        try {
          const d = JSON.parse(fs.readFileSync(path, 'utf8'));
          for (const [k, v] of Object.entries(d)) {
            if (!deps[k]) deps[k] = v;
          }
        } catch (e) { console.error('WARN: ' + path + ': ' + e.message); }
      };
      mergeFile('$CLOUD_MERGED');
      mergeFile('$FRONT_MERGED');

      // 3. Write merged package.json
      const sort = o => Object.fromEntries(Object.entries(o).sort(([a],[b]) => a.localeCompare(b)));
      const pkg = {
        name: 'shared-node-modules',
        private: true,
        description: 'Auto-generated by node-npm-deps.nix (static + cloud + front)',
        dependencies: sort(deps)
      };
      fs.writeFileSync('$PKG_JSON', JSON.stringify(pkg, null, 2) + '\n');
      console.log('[node-npm-deps] package.json: ' + Object.keys(deps).length + ' total packages');
    " || {
      printf "[node-npm-deps] WARN: merge failed\n"
    }

    # npm install if package.json changed
    if [ -f "$PKG_JSON" ]; then
      if [ ! -d "$NODE_MODULES/node_modules" ] || [ "$PKG_JSON" -nt "$LOCK" ]; then
        printf "[node-npm-deps] npm install: ~/.node_modules/\n"
        _npm_t0=$(date +%s)
        # --loglevel=error: EBADENGINE/peer-dep warn blocks were 100+ lines of
        # noise per switch drowning the 4 lines that matter; real failures
        # still print (and the || true keeps activation alive regardless).
        PATH="${nodejs}/bin:$PATH" $DRY_RUN_CMD ${nodejs}/bin/npm install \
          --prefix "$NODE_MODULES" \
          --no-audit --no-fund --legacy-peer-deps --loglevel=error || true
        printf "[node-npm-deps] npm install done in %ss\n" "$(( $(date +%s) - _npm_t0 ))"
      else
        printf "[node-npm-deps] ~/.node_modules/ is up to date\n"
      fi
    fi
  '';

  # Symlink node_modules into stdio MCP src/ dirs so ESM imports resolve.
  # NODE_PATH only works for CJS require() — ESM import ignores it and walks
  # the filesystem up from the importing file looking for node_modules/.
  home.activation.mcpNodeModulesSymlinks = lib.hm.dag.entryAfter ["sharedNodeModules"] ''
    SHARED="$HOME/.node_modules/node_modules"
    MCP_DIRS="
      $HOME/git/cloud/a_solutions/bc-obs_c3-specs-docs-mcp/src
      $HOME/git/cloud/a_solutions/ca-dat_c3-diego-personal-data-mcp/src
    "
    for dir in $MCP_DIRS; do
      [ -d "$dir" ] || continue
      target="$dir/node_modules"
      if [ -L "$target" ]; then
        continue  # already a symlink
      elif [ -d "$target" ]; then
        continue  # real node_modules, don't override
      fi
      ln -s "$SHARED" "$target"
      printf "[node-npm-deps] Symlinked %s -> shared node_modules\n" "$target"
    done
  '';
}
