# Front-end npm dependencies — merged from front-deps.json at activation time.
# Generated by front build system, synced to front-data/ by Dagu.
args@{ config, lib, pkgs, ... }:

let
  # Take nodejs from module args (flake.nix _module.args = pkgsUnstable
  # nodejs_22, i.e. >=22.12) — hardcoding pkgs.nodejs_22 here pinned every
  # npm install to 24.05's node 22.10, which vite 8 / unplugin 3 reject
  # (the EBADENGINE spam) and which native addons compiled against.
  nodejs = args.nodejs or pkgs.nodejs_22;
in {
  options.nodeNpmDeps.front = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = {};
    description = "Front-end npm dependencies (auto-merged from front-deps.json)";
  };

  # Activation: read front-deps.json → write merged output
  # body in scripts/merge-front-deps.sh
  config.home.activation.mergeFrontDeps = lib.hm.dag.entryBefore ["sharedNodeModules"] ''
    NODEJS_DIR="${nodejs}/bin" ${pkgs.bash}/bin/bash ${./scripts/merge-front-deps.sh} || true
  '';
}
