# Termux SSHD — declarative SSH daemon on port 8022, openssh-based.
#
# Recipe taken from the nix-on-droid maintainers (issue #32):
# https://github.com/nix-community/nix-on-droid/issues/32
#
# Why these specifics:
#   1. Run sshd via $HOME/.nix-profile/bin/sshd (the user-profile path),
#      NOT /nix/store/.../bin/sshd. The profile path is what nix-on-droid's
#      proot wrapper resolves correctly for privilege-separation re-exec.
#   2. Pass `-f <absolute>/sshd_config`. A real config file (with HostKey
#      and Port) works where inline `-o HostKey=...` flags fail under proot.
#   3. Connecting shells get `/bin/sh` which does NOT read `.bashrc` —
#      put nix env loading in `~/.profile` so PATH and tooling resolve.
#
# Provides: termux-sshd command (start|stop|status|restart)
# Trusted pubkeys: data-driven from data/authorized-keys.json.
{ config, pkgs, lib, ... }:

let
  # Pin sshd to 8.9p1 — short-term workaround. Real fix is the patched proot
  # below. Keep both: pin survives even if proot replacement fails.
  opensshPinned = pkgs.callPackage ../pkgs/openssh-pinned.nix { inherit pkgs lib; };

  # Patched proot-termux: implements execveat() with non-AT_FDCWD fd so
  # OpenSSH 9.x privsep / dropbear / apk-tools v3 don't die on child spawn.
  # See pkgs/proot-termux-patched/ for the patch + reasoning.
  prootPatched = pkgs.callPackage ../pkgs/proot-termux-patched {
    talloc = pkgs.pkgsStatic.talloc;
    stdenv = pkgs.stdenvAdapters.makeStaticBinaries pkgs.stdenv;
  };

  authData = builtins.fromJSON (builtins.readFile ./data/authorized-keys.json);
  authorizedKeysContent =
    lib.concatStringsSep "\n" authData.trusted_pubkeys + "\n";

  sshdScript = pkgs.writeShellScript "termux-sshd" ''
    # termux-sshd — POSIX wrapper for nix-on-droid sshd
    # Usage: termux-sshd [start|stop|status|restart]
    #
    # Hard-pinned to OpenSSH 8.9p1 (interpolated nix store path) to dodge
    # the proot execveat-with-fd limitation that breaks 9.x child processes
    # on Android. See pkgs/openssh-pinned.nix for the full story.

    SSHD_BIN="${opensshPinned}/bin/sshd"
    SSH_KEYGEN_BIN="${opensshPinned}/bin/ssh-keygen"

    PID_FILE="$HOME/.cache/sshd.pid"
    LOG_FILE="$HOME/.cache/sshd.log"
    HOST_KEY="$HOME/.ssh/ssh_host_rsa_key"
    SSHD_CONFIG="$HOME/.ssh/sshd_config"

    is_running() {
      [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null
    }

    do_start() {
      if is_running; then
        pid=$(cat "$PID_FILE")
        echo "sshd already running (PID $pid) on :8022"
        return 0
      fi

      mkdir -p ~/.ssh "$(dirname "$PID_FILE")"
      chmod 700 ~/.ssh

      # Host key — RSA (matches maintainer recipe; sshd accepts ed25519 too
      # but RSA is what they tested under proot).
      if [ ! -f "$HOST_KEY" ]; then
        "$SSH_KEYGEN_BIN" -t rsa -b 4096 -f "$HOST_KEY" -N "" -q
        echo "Generated host key: $HOST_KEY"
      fi

      # Write sshd_config (idempotent, regenerated each start so changes flow
      # through the wrapper without manual edits).
      cat > "$SSHD_CONFIG" <<EOF
    HostKey $HOST_KEY
    Port 8022
    PidFile $PID_FILE
    AuthorizedKeysFile $HOME/.ssh/authorized_keys
    PermitRootLogin no
    PasswordAuthentication no
    PubkeyAuthentication yes
    UsePAM no
    EOF
      chmod 600 "$SSHD_CONFIG"

      if [ -x "$SSHD_BIN" ]; then
        "$SSHD_BIN" -f "$SSHD_CONFIG" >> "$LOG_FILE" 2>&1
        sleep 0.5
        if is_running; then
          pid=$(cat "$PID_FILE")
          echo "sshd started (PID $pid) on :8022"
        else
          echo "sshd failed to start — last 10 lines of $LOG_FILE:"
          tail -10 "$LOG_FILE" 2>/dev/null | sed 's/^/  /'
          return 1
        fi
      else
        echo "ERROR: sshd not found at $SSHD_BIN (run nix-on-droid switch first)"
        return 1
      fi
    }

    do_stop() {
      if is_running; then
        pid=$(cat "$PID_FILE")
        kill "$pid" 2>/dev/null
        rm -f "$PID_FILE"
        echo "sshd stopped (was PID $pid)"
      else
        rm -f "$PID_FILE"
        echo "sshd not running"
      fi
    }

    do_status() {
      if is_running; then
        pid=$(cat "$PID_FILE")
        echo "sshd running (PID $pid) on :8022"
      else
        rm -f "$PID_FILE"
        echo "sshd not running"
      fi
    }

    case "''${1:-start}" in
      start)   do_start ;;
      stop)    do_stop ;;
      status)  do_status ;;
      restart) do_stop; sleep 0.3; do_start ;;
      *)       echo "Usage: termux-sshd {start|stop|status|restart}"; exit 1 ;;
    esac
  '';

  # ~/.profile — nix-on-droid maintainer recipe: SSH-spawned shells default to
  # /bin/sh which doesn't read .bashrc. Source the nix-on-droid session init
  # here so PATH, NIX_PATH, etc. are available in the SSH session.
  profileText = ''
    # Generated by sshd.nix — required for SSH sessions on nix-on-droid.
    # Without this, /bin/sh sessions have no nix tooling on PATH.
    if [ -r "$HOME/.nix-profile/etc/profile.d/nix-on-droid-session-init.sh" ]; then
      . "$HOME/.nix-profile/etc/profile.d/nix-on-droid-session-init.sh"
    elif [ -r "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
      . "$HOME/.nix-profile/etc/profile.d/nix.sh"
    fi
    [ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
  '';
in
{
  # Pinned OpenSSH 8.9p1 — wrapper interpolates its absolute store path so
  # there's no PATH ambiguity. Also expose it on PATH for ad-hoc use.
  home.packages = [ opensshPinned ];

  # Replace nix-on-droid's bundled proot with our patched build at activation
  # time. The hardcoded prootStatic option is `readOnly = true` in upstream
  # nix-on-droid (modules/environment/login/default.nix), so we can't override
  # via mkForce — we replace the file on disk after nix-on-droid's own
  # installProotStatic activation runs.
  #
  # IMPORTANT: the running proot mmap's /bin/proot-static. Replacing the file
  # affects only NEW proot processes (i.e. the next Termux app launch). After
  # the build, fully close the Termux app and reopen.
  home.activation.installPatchedProot =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      _src="${prootPatched}/bin/proot-static"
      _target="/data/data/com.termux.nix/files/usr/bin/proot-static"
      _bin_target="/bin/proot-static"

      if [ ! -f "$_src" ]; then
        echo "[patched-proot] WARNING: $_src missing, skipping"
        exit 0
      fi

      # Copy under a temp name then atomic-rename, in case the running
      # proot has the file open (which it always does for any active session).
      for _t in "$_target" "$_bin_target"; do
        if [ -e "$_t" ] || [ -L "$(dirname "$_t")" ]; then
          if ! cmp -s "$_src" "$_t" 2>/dev/null; then
            $DRY_RUN_CMD cp "$_src" "$_t.patched-tmp"
            $DRY_RUN_CMD chmod 755 "$_t.patched-tmp"
            $DRY_RUN_CMD mv -f "$_t.patched-tmp" "$_t"
            echo "[patched-proot] replaced $_t"
          fi
        fi
      done
      echo "[patched-proot] active on next Termux app launch"
    '';

  home.file.".local/bin/termux-sshd" = {
    source = sshdScript;
    executable = true;
  };

  home.file.".ssh/authorized_keys" = {
    text = authorizedKeysContent;
  };

  # ~/.profile loads nix env for ssh-spawned /bin/sh sessions
  home.file.".profile".text = profileText;

  programs.fish.shellInit = lib.mkAfter ''
    if not test -f $HOME/.cache/sshd.pid; or not kill -0 (cat $HOME/.cache/sshd.pid 2>/dev/null) 2>/dev/null
      termux-sshd start >/dev/null 2>&1
    end
  '';
}
