plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.diegonmarcos.superapp'
    compileSdk 34

    defaultConfig {
        applicationId 'com.diegonmarcos.superapp'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '0.1.0-dev'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation project(':libs:core')
    implementation project(':libs:updater')
    implementation project(':libs:mail')
    implementation project(':libs:cal')
    implementation project(':libs:feed')
    implementation project(':libs:net')
    implementation project(':libs:ops')
    implementation project(':libs:vault')

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
