# shared-node-modules — merge static+cloud+front deps into one package.json,
# npm install if changed. Env contract: NODEJS_DIR, STATIC_DEPS (JSON string).
NODE_MODULES="$HOME/.node_modules"
PKG_JSON="$NODE_MODULES/package.json"
LOCK="$NODE_MODULES/node_modules/.package-lock.json"
mkdir -p "$NODE_MODULES"
CLOUD_MERGED="$NODE_MODULES/.cloud-deps-merged.json"
FRONT_MERGED="$NODE_MODULES/.front-deps-merged.json"
[ -f "$PKG_JSON" ] && chmod u+w "$PKG_JSON" 2>/dev/null || true

PATH="$NODEJS_DIR:$PATH" CLOUD_MERGED="$CLOUD_MERGED" FRONT_MERGED="$FRONT_MERGED" PKG_JSON="$PKG_JSON" \
"$NODEJS_DIR/node" -e "
  const fs = require('fs');
  const deps = {};
  const staticDeps = JSON.parse(process.env.STATIC_DEPS);
  Object.assign(deps, staticDeps);
  const mergeFile = (path) => {
    if (!fs.existsSync(path)) return;
    try {
      const d = JSON.parse(fs.readFileSync(path, 'utf8'));
      for (const [k, v] of Object.entries(d)) {
        if (!deps[k]) deps[k] = v;
      }
    } catch (e) { console.error('WARN: ' + path + ': ' + e.message); }
  };
  mergeFile(process.env.CLOUD_MERGED);
  mergeFile(process.env.FRONT_MERGED);
  const sort = o => Object.fromEntries(Object.entries(o).sort(([a],[b]) => a.localeCompare(b)));
  const pkg = {
    name: 'shared-node-modules',
    private: true,
    description: 'Auto-generated by node-npm-deps.nix (static + cloud + front)',
    dependencies: sort(deps)
  };
  fs.writeFileSync(process.env.PKG_JSON, JSON.stringify(pkg, null, 2) + '\n');
  console.log('[node-npm-deps] package.json: ' + Object.keys(deps).length + ' total packages');
" || printf "[node-npm-deps] WARN: merge failed\n"

if [ -f "$PKG_JSON" ]; then
  if [ ! -d "$NODE_MODULES/node_modules" ] || [ "$PKG_JSON" -nt "$LOCK" ]; then
    printf "[node-npm-deps] npm install: ~/.node_modules/\n"
    _npm_t0=$(date +%s)
    # --loglevel=error: warn blocks were 100+ lines of noise per switch
    PATH="$NODEJS_DIR:$PATH" "$NODEJS_DIR/npm" install \
      --prefix "$NODE_MODULES" \
      --no-audit --no-fund --legacy-peer-deps --loglevel=error || true
    printf "[node-npm-deps] npm install done in %ss\n" "$(( $(date +%s) - _npm_t0 ))"
  else
    printf "[node-npm-deps] ~/.node_modules/ is up to date\n"
  fi
fi
